### ISSUE TITLE
detecting builtins

### ISSUE THREAD

**Issue by jimmywarting** [rollup/plugins#1048]
https://github.com/rollup/plugins/blob/12e1feecb833aa034d6677b1ec0ad76d4b81dc3b/packages/node-resolve/src/index.js#L167

i see that you are using sindres `builtin-modules` package to detect if something is builtin

One thing it dose not handle is sub modules and the node protocol, that's what his other related package: [is-builtin-module](https://github.com/sindresorhus/is-builtin-module) is for... it handles things like `node:fs`, `fs/promises` and `node:fs/promises`

Maybe you want to use is-builtin-module instead?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by jimmywarting** [comment]
yea, missed it cuz i used "references in a new issue"...

**Comment by shellscape** [comment]
That's the second time that's bit us. Major GitHub  fail there. Do me a solid and plop an appropriate template in there.
