### ISSUE TITLE
Plugin typescript: @rollup/plugin-typescript: outputToFilesystem option is defaulting to true.

### ISSUE THREAD

**Issue by fengxinming** [rollup/plugins#1099]
```js
{
    input: '/path/filename',
    plugins: [
      typescript(),
    ],
    output: {
      format: 'iife'
    }
  }
```

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by liucan233** [comment]
I resolved this problem.
change below run cli
`rollup --config rollup.config.ts --configPlugin @rollup/plugin-typescript`
to
`tsc --skipLibCheck --moduleResolution node --module esnext && mv rollup.config.js rollup.config.mjs`
then
`npm run config:rollup && rollup -c rollup.config.mjs`

this problem occurred because --configPlugin @rollup/plugin-typescript option.
