### ISSUE TITLE
[plugin-commonjs]: "Error: 'useState' is not exported by node_modules/react/index.js, imported by index.jsx;"

### ISSUE THREAD

**Issue by GarethChetwood** [rollup/plugins#1101]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version:^21.0.1
- Rollup Version:^2.53.2
- Operating System (or Browser):MacOS Catalina 10.15.7 Chrome v93.0.4577.82
- Node Version:v14.17.6
- Link to reproduction (⚠️ read below): https://replit.com/join/eitlhtkdna-garethchetwood

### Expected Behavior
The project builds successfully

### Actual Behavior
![image](https://user-images.githubusercontent.com/62290922/151836853-562603fb-725c-4e81-b84e-12f51e889794.png)

### Additional Information

I've created a small example with a few components and mostly similar config to mine. Just go to the repl link and do `npm install; npm run build`.

I've looked around about this error and the solution seems to be to use `namedExports` but that is now deprecated. Another solution seems to be to update to the latest rollup and commonjs plugin but I have done that and I'm still getting the error 😕 

Could be something I've done wrong in my config as I've been messing around with it a lot, but I've seen a few people flag up this exact issue, less a qualifying reproduction, so I thought I'd take a crack at it.

**Comment by lukastaegert** [comment]
Seems this is actually an issue for the babel plugin. So it has this message in its Readme that tells you to place it "after" the commonjs plugin https://github.com/rollup/plugins/tree/master/packages/babel#using-with-rollupplugin-commonjs

The reason is that the Babel plugin uses `import` statements to inject helpers. And those imports prevent the commonjs plugin from treating `react` as a commonjs dependency.

Now switching the order of plugins is not an option when you want to use JSX. Now you could add an acorn plugin that allows Rollup to parse JSX. But I think the "good" solution would be to fix the Babel plugin, e.g. like this:

* Babel detects if the commonjs plugin is used. If that is the case
* If a module contains import or export statements, or "no cjs keywords", we inject imports as usually
* Otherwise, we inject the helpers via require (for that we must detect if the commonjs plugin is present to not break the build)

Thoughts e.g. @Andarist ? This is a really common issue.

**Comment by Andarist** [comment]
Hmm, the suggestion is to use Babel **after** the commonjs plugin - so how does Babel injecting anything there prevent the commonjs plugin from treating those sources as CJS? I understand the detection mechanism used etc but I feel like I'm missing the order of the operations/transformations involved here and this prevents me from assessing the situation correctly.

Shouldn't CJS plugin "convert" CJS to ESM and **then** hand out the output to Babel?

**Comment by lukastaegert** [comment]
If there is an `import` in a file, it is no longer a CommonJS file. While the commonjs plugin now supports "mixed" modules with both imports and requires, for those modules it will only convert `require` expressions` but ignore `exports` and `module.exports` for exports.

The problem is: If the file contains non-JS syntax like JSX expressions, which is of course really common for React projects, then there needs to be a Babel instance BEFORE the commonjs plugin to convert the JSX syntax to plain JavaScript for the commonjs plugin to understand.

Another solution of course would be to run Babel twice, once before commonjs to convert just the JSX (and hopefully not need any imported helpers, or rather, inline the helpers), and once after that with shared helpers. But this would likely have quite a performance overhead, not mentioning that it is really complicated.

**Comment by lukastaegert** [comment]
So to refine my initial suggestion:
* Babel detects if the commonjs plugin is present and **placed AFTER the babel plugin**. Only then
* It tries to determine if a module contains import or export statements, in which case we can inject imports like before. Otherwise, we inject `require` expressions instead

**Comment by Andarist** [comment]
> The problem is: If the file contains non-JS syntax like JSX expressions, which is of course really common for React projects

It feels to me that CJS plugin should mainly be used to consume `node_modules` code that shouldn't contain JSX and the app code should just be authored in ESM. I know though that there are probably projects not strictly adhering to those "rules".

> Another solution of course would be to run Babel twice, once before commonjs to convert just the JSX (and hopefully not need any imported helpers, or rather, inline the helpers), and once after that with shared helpers. But this would likely have quite a performance overhead, not mentioning that it is really complicated.

Agreed.

> Babel detects if the commonjs plugin is present and placed AFTER the babel plugin. Only then

How a plugin would check such a thing?

> It tries to determine if a module contains import or export statements, in which case we can inject imports like before. Otherwise, we inject require expressions instead

This seems like a reasonable approach :+1:

> The advantage would be that this requires no additional setup by the user and my hope is that it would "just work". Question is, though, if this is easily feasible. I could also look into setting up a PR for this.

I think this has a huge potential of "just working". Some edge cases may arise when mixing CJS and ESM in a single file but quite frankly... I'm not super concerned about this. IMHO this should just be forbidden. With a detection strategy in place we could just detect CJS and ESM "mode" somewhat reliably and if a file is authored using a single module system then it should "just work".
