### ISSUE TITLE
the confusion of the use of compilerOptions.module for typescript

### ISSUE THREAD

**Issue by zzzgit** [rollup/plugins#1105]
<img width="249" alt="image" src="https://user-images.githubusercontent.com/1060733/153359732-01c72d5d-3561-4e4c-a0ab-3b7fdbb4ee2d.png">

According to the documentation above, `rollup-plugin-typescript` treats the config `compilerOptions.module` as the source module system from which the plugin will transfer the code to another module system.

However, according to the TS documentation, `tsc` will treat it as the target module system into which `tsc` will transfer the source code.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1060733/153376865-54e5629a-e711-4ee4-9c4b-c3af92624346.png">

The two documentations use `compilerOptions.module` in two different purposes of adverse directions. That's super confusing to us.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by zzzgit** [comment]
> _If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._
> 
> Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

No, I mean it's a conceptual conflict between the plugin and ts

**Comment by shellscape** [comment]
We have a modification template for this kind of scenario.
