### ISSUE TITLE
@rollup/plugin-typescript doesn't generate decalaration file

### ISSUE THREAD

**Issue by zzzgit** [rollup/plugins#1119]
It's hard to config this plugin `@rollup/plugin-typescript` to generate `*.d.ts`s.

Could you please offer an example repository to demonstrate to us?

**Comment by zzzgit** [comment]
I have taken one day to search and try every approach to generate d.ts. I haven't eaten lunch yet.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
