### ISSUE TITLE
[@rollup/plugin-typescript] Error: Could not load /home/runner/rollup-plugin-typescript-repl/input.ts: Debug Failure.

### ISSUE THREAD

**Issue by tscpp** [rollup/plugins#1136]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.3.1
- Rollup Version: 2.70.1
- Operating System (or Browser): Windows 11/Chrome
- Node Version: v12.22.10
- Link to reproduction: https://replit.com/@EliasSkogevall/rollup-plugin-typescript-repl

### Expected Behavior
I am using the plugin to generate javascript build files as well as typescript declaration files. I expect the build files to be generated at `output/` and the declarations files outputted at `types/`.

### Actual Behavior
I encountered this issue when trying to replicate another issue (#1137). ~~This does _not_ happen when I run rollup outside of the browsers, i.e. directly in my console.~~ Both locally, replit and stackbliz fail on the same error.

### Additional Information
```
./input.ts → ./output/bundle.js...
[!] (plugin typescript) Error: Could not load /home/runner/rollup-plugin-typescript-repl/input.ts: Debug Failure.
Error: Could not load /home/runner/rollup-plugin-typescript-repl/input.ts: Debug Failure.
    at getCommonSourceDirectoryOfConfig (/home/runner/rollup-plugin-typescript-repl/node_modules/typescript/lib/typescript.js:108428:313)
    at getOutputPathWithoutChangingExt (/home/runner/rollup-plugin-typescript-repl/node_modules/typescript/lib/typescript.js:108345:127)
    at getOutputDeclarationFileName (/home/runner/rollup-plugin-typescript-repl/node_modules/typescript/lib/typescript.js:108350:35)
    at getOwnOutputFileNames (/home/runner/rollup-plugin-typescript-repl/node_modules/typescript/lib/typescript.js:108393:23)
    at Object.getOutputFileNames (/home/runner/rollup-plugin-typescript-repl/node_modules/typescript/lib/typescript.js:108456:13)
    at findTypescriptOutput (/home/runner/rollup-plugin-typescript-repl/node_modules/@rollup/plugin-typescript/dist/index.js:444:33)
    at Object.load (/home/runner/rollup-plugin-typescript-repl/node_modules/@rollup/plugin-typescript/dist/index.js:802:28)

exit status 1
```
```javascript
import typescript from '@rollup/plugin-typescript';

export default {
  input: './input.ts',
  output: {
    file: './output/bundle.js',
    format: 'cjs',
  },
  plugins: [
    typescript({
      declaration: true,
      declarationDir: './types',
    }),
  ],
};
```

**Comment by nolanlawson** [comment]
For the record, I believe I've run into the same issue. After debugging, the issue seems to be that `parsedOptions.options.configFilePath` is undefined (not just missing, but literally `undefined`) when passed in to `ts.getOutputFileNames` here:

https://github.com/rollup/plugins/blob/e1a5ef99f1578eb38a8c87563cb9651db228f3bd/packages/typescript/src/outputFile.ts#L73-L84

I've managed to work around this by patching `@rollup/plugin-typescript` like so:

```patch
diff --git a/dist/es/index.js b/dist/es/index.js
index 6b7faa06d156797c31f2a33f0c5ae2d77b42d381..72467dc80d64b3af1b3bff76f62efb1a5b01b602 100644
--- a/dist/es/index.js
+++ b/dist/es/index.js
@@ -473,6 +473,8 @@ function getEmittedFile(fileName, emittedFiles, tsCache) {
  * containing files emitted by the Typescript compiler.
  */
 function findTypescriptOutput(ts, parsedOptions, id, emittedFiles, tsCache) {
+    // hopefully temporary fix for getting an assertion error here from typescript
+    parsedOptions.options.configFilePath = parsedOptions.options.configFilePath ?? '/tmp/fake.tsconfig.json'
     const emittedFileNames = ts.getOutputFileNames(parsedOptions, id, !ts.sys.useCaseSensitiveFileNames);
     const codeFile = emittedFileNames.find(isCodeOutputFile);
     const mapFile = emittedFileNames.find(isMapOutputFile);
```

Obviously this is sub-optimal, but I'm not sure what else to do since we don't actually have a `configFilePath` – in my case, I'm passing the `compilerOptions` directly into `@rollup/plugin-typescript` without a `tsconfig.json` file.

There already seems to be a repro above, and I'm afraid my repro is far from minimal, but if you'd like a repro:

```sh
git clone git@github.com:nolanlawson/heap-snapshot-toolkit.git
cd heap-snapshot-toolkit
git reset --hard f5b0ebd94a66f8c042e9adc6f55b44807c6f2f7d
cd ..

git clone git@github.com:ChromeDevTools/devtools-frontend.git
cd devtools-frontend
git reset --hard 0987a35390f74a2ecff9ac90e3531be5412c21fc

node --max-old-space-size=4096 ../heap-snapshot-toolkit/node_modules/rollup/dist/bin/rollup --config ../heap-snapshot-toolkit/scripts/devtools.rollup.config.js
```

This will throw the following error:

```
[!] (plugin typescript) Error: Could not load
    <...>/devtools-frontend/front_end/entrypoints/heap_snapshot_worker/HeapSnapshot.ts
    (imported by virtual:__entry__): Debug Failure.
```

`Debug Failure` is not very helpful, but by running `node` with `--inspect`, it indeed throws when TypeScript is trying to validate that the `parsedOptions.options.configFilePath` is defined:

![Image](https://github.com/user-attachments/assets/986bb729-a219-4690-b7f2-fb6abaed896c)

![Image](https://github.com/user-attachments/assets/b6afa0c5-97cf-42e9-9990-b46bd231e0db)

**Comment by robcresswell** [comment]
_sigh_, I hate stale bots; completely valid issue, with details, but yeah lets close it because nobody has bumped it for a while.

Anyway, another *same here* from me. Setting `tsconfig: false` causes this for me.

**Comment by shellscape** [comment]
@robcresswell read thressage the bot shared - step up, or refrain from posting more noise. This project is run by contribution. Further "same here" or bot debate will be removed.

**Comment by robcresswell** [comment]
I'm not entirely sure what the ideal approach is supposed to be then.

Agreeing that an issue is valid and naming the config option that caused it is considered toxic? Is the suggested route to let the valid issue be closed by the bot, then open a new issue with the same content and link to the old issue?
