### ISSUE TITLE
[@rollup/plugin-multi-entry] How do you control the bundle order of an array of inputs

### ISSUE THREAD

**Issue by RyanGuild** [rollup/plugins#1147]
- Rollup Plugin Name: @rollup/plugin-multi-entry
- Rollup Plugin Version: 4.1.0

Documentation Is:

- [x] Missing
- [x] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
I am working with an old codebase that did its own `umd`. In my mission to remove this code I am using rollup multi-entry to inject all the files and declaring our global in the `globals` section. This worked easily and compiled correctly however the order of the input files were not respected moving an important definition to the bottom of the iife.

my config
```js
export default {
  input: {
    // order here is important as the Vector3 is defigned in math.js
    include: [
      '3Dmol/WebGL/math.js',
      '3Dmol/WebGL/core.js',
      '3Dmol/WebGL/shapes.js',
      '3Dmol/WebGL/**/*.js',
      '3Dmol/3dmol.js',
      '3Dmol/colors.js',
     '3Dmol/*.js',
     'js/mmtf.js',
     '3Dmol/ui/ui.js',
     '3Dmol/ui/state.js',
     '3Dmol/ui/icon.js',
     '3Dmol/ui/form.js',
     '3Dmol/ui/defaultValues.js',
     '3Dmol/ui/**/*.js'
],
    exclude: [],
  },
  output: [
    {
      file: "build/3Dmol.js",
      name: "$3Dmol",
      format: "umd",
      sourcemap: true,
      strict: true,
      exports: "none",
      externalLiveBindings: true,
      extend: true,
    }
  ],
  plugins: [multi()]
}
```

### Your Proposal for Changes

Update the documentation to reflect what is going on here. Whether this is deterministic or not? If it is deterministic what is the order of the modules bundled?

**Comment by shellscape** [comment]
This looks like a support request, which we (maintainers) don't offer here. I understand that you want some documentation around your specific use-case, but because it's specific to your needs rather than an overarching community need, it's mostly asking for support 😄  For that reason, we're going to close this as a support request, but the community is still welcome to comment and help you out. You might also try the [Rollup Discord](https://is.gd/rollup_chat)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.
