### ISSUE TITLE
IS it possible to prevent window.* pollution if a module has `window.ejs = exports;`?

### ISSUE THREAD

**Issue by mercmobily** [rollup/plugins#1154]
I am trying to make an ES6 module out of EJS. I managed! However, the source has this:

````
if (typeof window != 'undefined') {
  window.ejs = exports;
}
````

This means that the resulting module ALSO has that.
Barring running a regex on the source file, is there a neat way of preventing the module from polluting `window`?

I made a reproduction replit for it: https://replit.com/@mercmobily/prevent-namespace-pollution#ejs-es.js
The source is `node_modules/ejs/lib/ejs.js` which ends with:

````
/* istanbul ignore if */
if (typeof window != 'undefined') {
  window.ejs = exports;
}
````

And obviously so does the resulting ES6 module.
I am in talks to the author of EJS who is happy to make minor changes, but not drastic ones.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by mercmobily** [comment]
Missed it. Apologies.
