### ISSUE TITLE
Issue when testing code using Jest which references aliases

### ISSUE THREAD

**Issue by mikeerickson** [rollup/plugins#1157]
Assuming the following pseudo code, how can I import these modules using Jest (see error at the bottom)

File A

```
import Module from '@helpers/Module'
```

File B (Jest test)

```
import AnotherModule from '../lib/AnotherModule'
```

Produces this error when running Jest

```
Cannot find module '@helpers/Module' from 'abc/lib/AnotherModule.js'
```

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
