### ISSUE TITLE
[typescript] plugin-typescript doesn't emit helper funtion definition when input is a single module

### ISSUE THREAD

**Issue by csr632** [rollup/plugins#1188]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.3.2
- Rollup Version: 2.74.0
- Operating System (or Browser): MacOS
- Node Version: v
- Link to reproduction _(⚠️ read below)_: https://replit.com/@csr632/rollup-ts-issue

### Expected Behavior

Output code should be runnable.

### Actual Behavior

Output code contains undefined function like `__assign`. The definitions of helper functions are not emmitted.

### Additional Information

It will work if we import other modules in the entry module.

**Comment by kokovtsev** [comment]
I also faced this issue and found a solution thanks to your report.

Note for maintainers: I guess that very few real projects don't have any imports, however people _starting_ a project from zero can easily stumble upon this and have hard time debugging the problem. In my case, I started with a single `async` function, which was failing because of missing helpers.

That said, fixing this would likely improve the developer experience for many people
