### ISSUE TITLE
`types` must common first in `exports` field

### ISSUE THREAD

**Issue by JounQin** [rollup/plugins#1218]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@rollup/pluginutils@3.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@rollup/pluginutils/package.json b/node_modules/@rollup/pluginutils/package.json
index 0f57f41..3089eef 100644
--- a/node_modules/@rollup/pluginutils/package.json
+++ b/node_modules/@rollup/pluginutils/package.json
@@ -76,6 +76,7 @@
     ]
   },
   "exports": {
+    "types": "./types/index.d.ts",
     "require": "./dist/cjs/index.js",
     "import": "./dist/es/index.js"
   },
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

---

More details: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing

**Comment by JounQin** [comment]
There seems already #1196 for fixing, keep it open before resolved.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
