### ISSUE TITLE
[commonjs] strictRequires indent with \t modifies multi-line string values.

### ISSUE THREAD

**Issue by simonbuchan** [rollup/plugins#1228]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 22.0.1
- Rollup Version: 2.77.2
- Operating System (or Browser):
- Node Version: v16.16.0
- Link to reproduction: https://replit.com/@simonbuchan/rollup-plugin-repro#output/bundle.js

### Expected Behavior
Multiline-string values should be preserved.

### Actual Behavior
Indent `\t` characters are blindly inserted into the multi-line string.

### Additional Information
This particular issue seems to be due to:

https://github.com/rollup/plugins/blob/add3a350e99505e15790b4915c33b1fcc5bf00ec/packages/commonjs/src/transform-commonjs.js#L534

but there are other uses of `magicString.indent("\t")` in the code-base, e.g.:

https://github.com/rollup/plugins/blob/add3a350e99505e15790b4915c33b1fcc5bf00ec/packages/commonjs/src/generate-exports.js#L12-L16

The simple fix is just don't indent code - I doubt it would be simple to implement a correct source-map-preserving indent. Perhaps instead doing a transform from multi-line template strings to single-line escape codes would also work?

**Comment by lukastaegert** [comment]
Actually considering that the plugin is already parsing the entire code and knows all template literals, the fix is to pass an `indentExclusionRanges ` array to the MagicString constructor and for every `TemplateLiteral`, push `[start, end]` into the array. This should actually be done for regular `Literal`s as well as you can escape a line-break in a string. This is how Rollup does it https://github.com/rollup/rollup/blob/release-3.0.0/src/ast/nodes/TemplateLiteral.ts#L57-L57 https://github.com/rollup/rollup/blob/release-3.0.0/src/ast/nodes/Literal.ts#L88-L88, see also https://github.com/Rich-Harris/magic-string#usage

**Comment by simonbuchan** [comment]
As a workaround for now, I'm flattening multi-line strings with:

```
import * as babelTypes from "@babel/types"

import babel from "@rollup/plugin-babel";
import commonjs from "@rollup/plugin-commonjs";

export default {
  ...
  plugins: [
    ...
    babel({
      skipPreflightCheck: true,
      babelHelpers: "external",
      babelrc: false,
      configFile: false,
      plugins: [babelPluginFlattenTemplate()],
    }),
    commonjs(),
    ...
  ],
};

function babelPluginFlattenTemplate(): babel.PluginObj<unknown> {
  return {
    visitor: {
      TemplateElement(path) {
        const value = path.node.value;
        if (value.raw.includes("\n")) {
          path.replaceWith(
            babelTypes.templateElement({
              raw: value.raw.replace(/\n/g, "\\n"),
              cooked: value.cooked?.replace(/\n/g, "\\n"),
            }),
          );
        }
      },
    },
  };
}
```
