### ISSUE TITLE
@rollup/plugin-node-resolve giving "TypeError: require(...) is not a function", rollup-plugin-node-resolve works fine

### ISSUE THREAD

**Issue by mercmobily** [rollup/plugins#1234]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 13.1.3
- Rollup Version: 2.70.1
- Operating System (or Browser): Linux
- Node Version: 12.22.8
- Link to reproduction: https://replit.com/@mercmobily/rollup-plugin-repro

### Expected Behavior

I expect the build to work.

(Please note: this is a repost of #1153, which I am sure was closed by accident. This is a full bug report, which comes with reproduction steps etc. It somehow became stale.)

### Actual Behavior

The build doesn't work as it gives a TypeError

### Additional Information

Changing `@rollup/plugin-node-resolve` into `rollup-plugin-node-resolve` (the old deprecated one), it works. Note that `package.json` includes both, so that it's easy to swap them around.

**Comment by shellscape** [comment]
#1153 was closed as stale because no one picked it up. 

> Hey folks. This issue hasn't received any traction for 60 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it. [ⓘ](https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea)

It wasn't closed by accident. It was closed following the stale issue policy we have set. So as not to be difficult, I won't close this as a duplicate, but it should be. If you want your issue to gain traction, you'll need to contribute a fix, hope that a maintainer (of which we have very few active right now) picks it up, or lobby the community to step in and contribute a fix. If there had been any more meaningful triage or discussion on your issue, we would have reopened it. This org simply does not have the maintainer activity to take up every issue, so the community must take a stake in it.

If this issue is closed as stale, as the other one was, please do not create another duplicate.

**Comment by mercmobily** [comment]
Sorry to hear that you are missing maintainers. This is an awesome project! I will try and have a look myself, but I don't know the codebase enough. Thanks for the explanation.

**Comment by shellscape** [comment]
check out the reply by @tjenkinson on #1153. looks like you might be requiring incorrectly

**Comment by mercmobily** [comment]
Oh my. Thanks!
