### ISSUE TITLE
commonjs's resolver breaks moduleSideEffects treeshaking even for esm-only code

### ISSUE THREAD

**Issue by simonbuchan** [rollup/plugins#1244]
- Rollup Plugin Name: commonjs (I guess?)
- Rollup Plugin Version: 22.0.2
- Rollup Version: 2.78.0
- Operating System (or Browser): windows 11
- Node Version: 16.16.0
- Link to reproduction: https://replit.com/@simonbuchan/rollup-plugin-commonjs-treeshake#output/bundle.js

### Expected Behavior

Due to `"sideEffects": false`, the content of `evil.js` should not be included in the bundle:

```
Object.prototype.evil = "don't expect this to be here";
```

### Actual Behavior

When `commonjs()` is included in `plugins`, the side effects are included, despite there being no require / exports or other required transformations.

### Additional Information

AFAICT, this is essentially what breaks the majority of tree-shaking out there, `lodash-es`, `@aws-sdk`, etc...

This seems to be due to the injected `commonjs--resolve` plugin, replacing `commonjs()` with: `{ ...commonjs(), options: undefined }`, which prevents this injection causes the issue to go away.

Injecting logging after said injected plugins' `resolveId` shows it returning each module twice, first with `moduleSideEffects` set to true, then set to false. Not sure why the same plugin `resolveId` is being called twice, with the same options even.

The upshot seems to be that the `moduleSideEffects` value from, e.g. `@rollup/plugin-node-resolve` is getting dropped by `commonjs`.

**Comment by lukastaegert** [comment]
Looking into this. It is slightly more tricky than it seems. Not sure if the fix would need to be in commonjs, node-resolve, or even in rollup core as it is the very specific ping-pong interplay of the two plugins that is causing the issue here.

**Comment by simonbuchan** [comment]
Yep, I took several hours trying to figure out what's going on even when I had a repro, with little luck. If you have any specific pointer's I'm happy to take a deeper look this weekend?

**Comment by lukastaegert** [comment]
Well, the problem is that both commonjs and node-resolve are using `this.resolve` to pre-resolve the id before doing something with it. So what happens is
- commonjs--resolver goes first (as it should) and asks all other plugins what to do with the id
- node-resolve gets the call, resolves the id, but then it puts the resolved id back into a `this.resolve` to see if some other plugin e.g. thinks this id should be external. Even though commonjs--resolver used `skipSelf` to prevent back calls, this does not prevent calls with different ids from being handed back via `this.resolve` and so the call gets back, this time with a skipSelf from node-resolve
- commonjs--resolver now again asks all other plugins what to do with the resolved id. But this time, node-resolve is skipped (due to the previous skipSelf), so `moduleSideEffects` are not returned correctly.
- and now comes the critical part, commonjs--resolver then passes the id to `this.load`, and it is the second result that is used, the one without `moduleSideEffects`. Once an id is passed to `this.load`, other `this.resolve` can no longer change the value of `moduleSideEffects`.

So I See two possible solutions
1. node-resolve manually fixes moduleSideEffects afterwards by using `this.load` itself, then it gets access to a mutable copy of the module options, or
2. we change the logic in Rollup core so that the value of moduleSideEffects is not ignored for subsequent resolves

I am leaning to implement the second option as this is kind of a pain point. You can have a look if you want, otherwise I want to start working on this tomorrow.

**Comment by simonbuchan** [comment]
Is there good reason to assume the first plugin to return any value for `moduleSideEffects` is correct? It sounds about right to me.

**Comment by simonbuchan** [comment]
Pushed a [test](https://github.com/rollup/rollup/pull/4615), results are:

```
  1) rollup
       function
         module-side-effects
           first-resolve-id-wins: does not include modules without used exports if moduleSideEffect is false:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  {
    'sideeffects-false-usereffects-false': false,
    'sideeffects-false-usereffects-false-unused-import': false,
    'sideeffects-false-usereffects-false-used-import': false,
+   'sideeffects-false-usereffects-true': true,
+   'sideeffects-false-usereffects-true-unused-import': true,
+   'sideeffects-false-usereffects-true-used-import': true,
-   'sideeffects-false-usereffects-true': false,
-   'sideeffects-false-usereffects-true-unused-import': false,
-   'sideeffects-false-usereffects-true-used-import': false,
    'sideeffects-null-usereffects-false': false,
    'sideeffects-null-usereffects-false-unused-import': false,
...
    'sideeffects-null-usereffects-true-unused-import': true,
    'sideeffects-null-usereffects-true-used-import': true,
+   'sideeffects-true-usereffects-false': false,
+   'sideeffects-true-usereffects-false-unused-import': false,
+   'sideeffects-true-usereffects-false-used-import': false,
-   'sideeffects-true-usereffects-false': true,
-   'sideeffects-true-usereffects-false-unused-import': true,
-   'sideeffects-true-usereffects-false-used-import': true,
    'sideeffects-true-usereffects-true': true,
    'sideeffects-true-usereffects-true-unused-import': true,
    'sideeffects-true-usereffects-true-used-import': true
  }
```

Does that seem right?

**Comment by lukastaegert** [comment]
Will need to check. But the problem is exactly that it is only taking the first attributes because of the usage of `this.load` while in fact it should use the last one.

**Comment by simonbuchan** [comment]
I'll admit I don't really understand the interaction `this.load` has here: if it's necessary for this `commonjs` issue, there might be two issues?

The above results are for, roughly:

```
plugins: [
  { name: "outer", async resolveId(id, importer) { await this.resolve(id, importer, { skipSelf: true }); return { id }; },
  { name: "inner", resolveId(id) { return { id, moduleSideEffects: JSON.parse(id.split('-')[1]) }; },
],
```

So when I say the "first to return any value for `moduleSideEffects`", I mean the first to *return*, e.g. "inner", here - I'm unclear if you meant the same thing - "first" is annoyingly ambiguous here!

Thinking about it further, though, the problem seems to be not that it's taking the last, but that it's ignoring any "inner" calls, and applies the `options.treeshaking.moduleSideEffects` result as a default to the outermost call only, rather than collecting all the results so far - but only where it's actually defined.

Specifically, this makes `options.treeshaking.moduleSideEffects` a default if *no* `resolveId` returned a value for `moduleSideEfffects`.

E.g. if "outer" above returned `{ moduleSideEffects: false }`, that would mean it saw the result of `this.resolve()`, and still decided that whatever transform it will do makes the "inner" `moduleSideEffects` irrelevant, and that it will now never have side effects - I think this preserves enough flexibility that plugins can still do what they want?

If this commonjs issue would still happen due to `this.load` even with the above change, then I think I'd need to bust out a sequence diagram...

**Comment by lukastaegert** [comment]
So the problem is there is exactly one moment when the flag is fixed, and it is when the module is loaded, either because Rollup requested the id to be resolved and now it is loaded, or because a plugin explicitly uses `this.load`. And if the call to `this.load` does not contain the flag from the node-resolve plugin, then no resolver can change the flag after that. My idea was to change this so that later resolvers CAN change the flag, but it turns out this breaks the commonjs plugin in another way, because the plugin sets the `syntheticNamedExports` flag in the `transform` hook, and that value is now also overwritten by subsequent resolvers.
Next, I will try another approach: Fixing by changing `node-resolve` so that it does not skip itself in its own `this.resolve` call but adds the correct meta information so that the commonjs plugin does the right thing. I will report back tomorrow.
