### ISSUE TITLE
plugin request: Handle data:mime,<data> urls

### ISSUE THREAD

**Issue by frank-dspeed** [rollup/plugins#125]
Request Checklist:

- [x] I have searched https://npmjs.com/ before opening this issue
- [x] I have searched https://github.com/rollup/awesome before opening this issue

### New Plugin Use Case

I would like to import code as a module from a `data:{mime}` declaration. 

```js
import 'data:text/javascript, console.log('Buhhh')'
import me from 'data:application/json, { "my": 'json''}
import('data:application/json, { "my": 'json''})
``` 

### New Plugin Proposal

Perhaps `@rollup/plugin-data-mime`. The plugin could look like:

```js
{
  resolveId(id) {
    if (isDataUrl(id)) {
      return id;
    }
    return null;
  },
  load(id) {
    if (isDataUrl(id)) {
      return getCodeFromDataUrl(id);
    }
    return null;
  }
}
```

**Comment by shellscape** [comment]
@frank-dspeed thanks for opening an issue here for this. I've updated your issue with the content from the original rollup/rollup issue. That's the better way to go, since plugin maintainers and contributors are more likely to take up the effort without the extra friction of referencing and parsing another issue (we're all operating here on limited, volunteered time and availability.)

**Comment by shellscape** [comment]
For reference, here's Node's documentation on this import approach https://nodejs.org/api/esm.html#esm_data_imports

**Comment by shellscape** [comment]
I've begun work on this plugin.

@LarsDenBakker saw your comment on the webpack issue and thought this might interest you.

**Comment by LarsDenBakker** [comment]
Indeed I need one as well, I ended up writing my own but it's good to standardize.

**Comment by frank-dspeed** [comment]
@LarsDenBakker yes i need it also for my esm-loader module to support cross platform importScript
