### ISSUE TITLE
plugin-wasm: Generates incorrect code for format "es"

### ISSUE THREAD

**Issue by Alfred-Mountfield** [rollup/plugins#1357]
- Rollup Plugin Name: @rollup/plugin-wasm
- Rollup Plugin Version: 6.0.1
- Rollup Version: 3.1.0
- Operating System (or Browser): MacOS 12.5.1 (M1)
- Node Version: 18.7.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@Alfred-Mountfield/plugin-wasm

### Expected Behavior

The generated dist to be importable as an ES-Module using Node's native support

### Actual Behavior

```sh
var fs = require("fs");
         ^
ReferenceError: require is not defined in ES module scope, you can use import instead
```

### Additional Information

Now that node has native support for ESM, I'd expect the plugin to be format aware and to able to generate a node-compatible ESM module, but it seems to [naively just paste the following snippet](https://github.com/rollup/plugins/blob/ca7a6684c7ea35c375a01ffda762f62b4aba2152/packages/wasm/src/helper.ts#L6-L9).

**Comment by nickbabcock** [comment]
Hey Alfie, I agree that what you want makes sense.

It sounds like you already have a bit of a solution in mind (or how a solution would work), by having the plugin be format aware. Can you elaborate on how this would work?

Some questions:

- How does one determine the desired format when not explicitly supplied?
- If it requires interpreting package.json, are there are other rollup plugins that do this too?
- Would it support detection of a package.json that includes a node.js commonjs export?

This seems like it could lead to a complicated plugin, but definitely an enticing thought depending on what you have in mind.

Maybe there is an incremental step we can take first. Like introduce a new `targetEnv` of `node-esm`. I think it has to be a standalone target like `node-esm` with the `auto` target continuing to use `require`, due to imports needing to be at the top of the file iirc. And I don't think dynamic imports would fit when synchronous compilation is requested.

It's not immediately apparent to me what the best way to hoist the import to the top of the emitted file would be (rollup may have a simple way to due this, I'm just not knowledgeable in this subject).
