### ISSUE TITLE
defaultIsModuleExports: 'auto' is not processed right in getEsImportProxy function

### ISSUE THREAD

**Issue by flyingbirdhub** [rollup/plugins#1359]
relate to the issue https://github.com/rollup/plugins/issues/1209, here reopen the issue and discuss the solution

and the solution may be https://github.com/rollup/plugins/pull/1358

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
