### ISSUE TITLE
@rollup/plugin-replace does not support replacing strings with a leading '@'

### ISSUE THREAD

**Issue by matthew-ia** [rollup/plugins#1419]
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: 5.0.2
- Rollup Version: 2.3.4
- Operating System (or Browser): macOS 13.0
- Node Version: v19.4.0
- Link to reproduction https://github.com/matthew-ia/test-rollup-plugin-replace

### Expected Behavior

Replacement strings that start with `@` should be replaced. E.g., if a user configures '@FOO' to be replaced with 'bar', it should work.

### Actual Behavior

Strings with a leading with `@` do not get replaced.

### Additional Information

For example, given this config:
```js
plugins: [
  replace({
    '@FOO': 'bar',
  }),
]
```
And this source HTML:
```html
<p>@FOO</P>
```
The **expected** output HTML is:
```html
<p>bar</p>
```
But the **actual** output HTML is the same as the source:
```html
<p>@FOO</P>
```

I couldn't find documentation that a leading `@` is not allowed for replacements.

**Comment by shellscape** [comment]
This is because the default [`delimiters`](https://github.com/rollup/plugins/tree/master/packages/replace#delimiters) include a leading word-boundary `\b` character, which `@` is not. There's no bug in the plugin given that, but documentation could be improved for strings with leading non-word characters. The solution will be to provide a set of delimiters (which are regex fragments) that have a negative lookback for `@` so that the target string `@FOO` can also have a leading `@`.

We're open to a PR that adds some documentation to the `delimiters` option for implementing this, but as it's not a bug, this will be closed.

**Comment by shellscape** [comment]
FWIW `(\b|(\B|@))` may work as the first delimiter in your use case.
