### ISSUE TITLE
rollup/commonjs plugin sometimes fails to detect circular dependency

### ISSUE THREAD

**Issue by dskloetd** [rollup/plugins#1425]
- Rollup Plugin Name: rollup/plugin-commonjs 
- Rollup Plugin Version: 24.0.0
- Rollup Version: 3.12.0
- Operating System (or Browser): MacOS 13.2 (or Chrome 109.0.5414.119 (Official Build) (arm64) )
- Node Version: 18.13.0
- Link to reproduction _(⚠️ read below)_: https://github.com/dskloetd/rollup-bug

### Expected Behavior

All modules with circular dependencies should be wrapped in a "require wrapper".

### Actual Behavior

The CommonJS plugin in rollup has a bug where it sometimes fails to detect a
circular dependency. The issue that [this call to isCyclic](https://github.com/rollup/plugins/blob/69146cdf1f7353aa72364f69fa5e49c732a1abd8/packages/commonjs/src/resolve-require-sources.js#L72)
happens before the dependency graph is fully built and so
`loadModule(resolved)` might be skipped while it shouldn't be.
And then `getTypeForFullyAnalyzedModule`
[here](https://github.com/rollup/plugins/blob/69146cdf1f7353aa72364f69fa5e49c732a1abd8/packages/commonjs/src/resolve-require-sources.js#L188)
is called before the module is indeed fully analyzed. Then the module doesn't
get a "require wrapper" while it does need one.

**Comment by lukastaegert** [comment]
There are indeed some problematic edge cases in the logic. Even worse, it can be that depending on race conditions in the module resolution, the output can become non-deterministic with regard to which modules are wrapped.
For that reason (and because the logic is really complicated) I am considering removing that logic again and instead to make `strictRequires: true` the default, with the option to manually opt out of this behavior for some or all modules.

**Comment by dskloetd** [comment]
Non-deterministic builds is indeed how I discovered the issue in the first place.

**Comment by dskloetd** [comment]
disappointing
