### ISSUE TITLE
Impossible to escape special characters in include/exclude patterns handled by createFilter

### ISSUE THREAD

**Issue by Artur-** [rollup/plugins#1430]
- Rollup Plugin Name: `@rollup/pluginutils`
- Rollup Plugin Version: 5.0.2
- Rollup Version: 3.10.0
- Operating System (or Browser): mac os Ventura
- Node Version: 18.12.1
- Link to reproduction: https://stackblitz.com/edit/rollup-repro-q5av61?file=src%2Fmain.js

### Expected Behavior
An include/exclude pattern allows special picomatch characters to be escaped using `\`
A pattern like `'**/*\\?*.js'` should match js files with a `?` in the filename

### Actual Behavior
Any `\\` in the pattern is converted into `/` by `createFilter`, making it impossible to escape any characters such as `?` 
A pattern like `'**/*\\?*.js'` is converted into `'**/*/?*.js'` which has a completely different meaning

**Comment by benmccann** [comment]
I'm guessing that's coming from here: https://github.com/rollup/plugins/blob/17865bcdde3dd18fc3da25ef9548c5bd5445ff19/packages/pluginutils/src/normalizePath.ts#L5

**Comment by benmccann** [comment]
I think this should be fixed by removing the calls to `normalizePath` - though that would be a breaking change. Is there any really compelling reason it's critical to support the `\` syntax as a path separator? I don't think there would be a way to fix this without remove the normalization because you wouldn't be able to tell when you want `\` to be converted to `/` and when you don't.
