### ISSUE TITLE
Regression introduced in @rollup/plugin-typescript 11.1.2

### ISSUE THREAD

**Issue by divdavem** [rollup/plugins#1531]
- Rollup Plugin Name: @rollup/plugin-typescript 
- Rollup Plugin Version: 11.1.2
- Rollup Version: 3.26.0
- Operating System (or Browser):  Ubuntu 22.04.2 LTS
- Node Version: 16.20.1
- Link to reproduction: https://github.com/AmadeusITGroup/protractor-to-playwright/commit/1c63c1d6f3fac241e6181b654f5ef82771772bdb, cf [failing build](https://github.com/AmadeusITGroup/protractor-to-playwright/actions/runs/5443794770/jobs/9900780350)

### Expected Behavior
Switching from version 11.1.1 to 11.1.2 should not break the build.

### Actual Behavior
Switching from version 11.1.1 to 11.1.2 [breaks the build](https://github.com/AmadeusITGroup/protractor-to-playwright/actions/runs/5443794770/jobs/9900780350).

The following error is displayed:

```
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

It looks like typescript to javascript conversion is skipped in 11.1.2 in this project.

Going back to version 11.1.1 fixes the build, cf [this commit](https://github.com/AmadeusITGroup/protractor-to-playwright/commit/6997c3534b413d95e6056e720cb106ffa5c8c0d5)

**Comment by shellscape** [comment]
What you provided is not a valid reproduction. Please feel free to open a PR with a test which fails and shows the regression; we have tests designed to prevent regressions. Or provide a vid reproduction.

**Comment by divdavem** [comment]
@shellscape Thank you for your answer. I don't have time to work on this right now. I just wanted to notify you of the regression. Now you have all the necessary information to reproduce it. It may happen on other projects too.

**Comment by shellscape** [comment]
> Now you have all the necessary information to reproduce it

We actually don't, because you didn't provide a reproduction, which is precisely why we require one. I'd advise you to look closer at a project's requirements within issue templates.

If this were a wide-spread problem, we'd immediately know as 350k+ users updated to the latest patch version. What you have is what we call an "edge case." And without providing an isolated reproduction, the team cannot take up your issue, cannot provide any help with triage, and cannot begin to work on a fix - if one is needed.

This is likely a nuanced issue with your specific configuration in your specific environment.

Wish you and your team success.

**Comment by GastonZalba** [comment]
Hi, i have the same problem here. So far I've checked 3 builds failing and 2 still working correctly. In all cases, restoring to version 11.1.1 fixes the problem (broadly speaking, they all have the same configuration). I will try to make a valid reproduction in the next days, but from what I see the problem is difficult to trace because if the `.rollup.cache` folder made with a build from a previous version persists, the error does not occur. So it can happen that when updating (from version 1.11.1) the build it is still generated correctly, but fails iafter the cache is cleared (or if it is a clean installation)
