### ISSUE TITLE
ignores 'import ... =' in cjs output

### ISSUE THREAD

**Issue by vdegenne** [rollup/plugins#166]
- Rollup Version: 1.29.0
- Operating System (or Browser): Fedora 31/Chrome (last)
- Node Version: 13.6.0

### How Do We Reproduce?
- install `koa-bodyparser`, `@types/koa-bodyparser`, `rollup` and typescript plugins
- then create the files
*input.ts*
```typescript
import bodyParser = require('koa-bodyparser');
console.log(bodyParser);
```
*rollup.config.js*
```javascript
import typescript from '@rollup/plugin-typescript';

export default {
  input: 'input.ts',
  output: { file: 'output.js', format: 'cjs' },
  plugins: [typescript()]
}
```
- run `rollup` targeting `cjs`

### Expected Behavior
*output.js*
```javascript
'use strict';
const bodyParser = require('koa-bodyparser');
console.log(bodyParser);
```
output of vanilla typescript.

### Actual Behavior
```javascript
'use strict';
console.log(bodyParser);
```
generates an empty file.

**Comment by shellscape** [comment]
_If you are sure this is a bug, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by vdegenne** [comment]
I am very confused, now it works after I went to take my food,
rollup digests the following : 

```javascript
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var bodyParser = _interopDefault(require('koa-bodyparser'));
```

Maybe it was just a temporary file or the watcher messing the output I don't know. Sorry for this useless matter.

**Comment by vdegenne** [comment]
I reopen the issue and I changed my original post using the issue template because I think this is a bug.
(originated from : https://github.com/rollup/rollup/issues/3341)

**Comment by lukastaegert** [comment]
Another thought from the Rollup issue:
- Typescript NEEDS to be configured to output CJS in order for this import style to be supported at all. Not sure if the plugin supports that
- Rollup NEEDS the CJS plugin in order to consume such output

My best guess is that the plugin tries to target ESM as this is the only format natively support by Rollup and at the same time does not emit the warning you get when doing that in the TS playground

I would assume that it works correctly if you just switch to either

`import bodyParser from...` or `import * as bodyParser from...`, no matter what the documentation of bodyParser says

**Comment by vdegenne** [comment]
> Typescript NEEDS to be configured to output CJS in order for this import style to be supported at all. Not sure if the plugin supports that

You mean in the `tsconfig.json` ? I set `module` to `commonjs` already.

> Rollup NEEDS the CJS plugin in order to consume such output

I also included the CJS plugin in the plugins array but still the import is not converted in the output.

I try everything possible before filing an issue and this particular one was bugging me to the point I had to open one, thought this could interest you because as a fallback and as you mentioned I can use the classic `import ... from` syntax so it's not like I don't have an immediate solution but again this is at least reported. Thanks again.

**Comment by NotWoods** [comment]
The plugin should work if the module type is set to commonjs and the commonjs plugin is included. We have an existing test for this behavior. I'll look into it and see if my other changes nfix the issue.

**Comment by NotWoods** [comment]
@vdegenne Does configuring the plugin as `typescript({ module: 'commonjs' })` fix the issue?

**Comment by vdegenne** [comment]
@NotWoods Sorry for the late reply.
I tried as you said, now it includes `const bodyParser = require('koa-bodyparser')` which is great but now all my default local imports are excluded from the build for instance

```typescript
import myvar from './local/module'; // export default myvar = 'test';
``` 

is translated to

```javascript
const myvar_1 = tslib_1.__importDefault(require("./local/module"));
```

I'd expect rollup to bundle that as well because they are local sources (not from the `node_modules` directory).

I tried to update to the last version of `@rollup/plugin-typescript` (3.0.0) but the problem persists, even worst if I just use `typescript()` it doesn't fallback to the previous output but instead the tslib `importDefault` function wrap all my local default import.

**Comment by shellscape** [comment]
@NotWoods housekeeping: think this is still relevant?

**Comment by NotWoods** [comment]
I haven't found any solutions for this so we may want to close as won't fix for now. Typescript appears to only allow this syntax if you emit common js code.

**Comment by shellscape** [comment]
Aye aye
