### ISSUE TITLE
Error on importing legacy plugin Uncaught TypeError: Cannot set property 'payment' of undefined

### ISSUE THREAD

**Issue by kristjankoppel** [rollup/plugins#200]
Hi!

I'm trying to import a legacy plugin in my JS file. 
And i use Rollup legacy plugin to be able import https://github.com/stripe/jquery.payment plugin in my final file. The import is made but then JS hits me with  "Uncaught TypeError: Cannot set property 'payment' of undefined" error that comes after this legacy plugin is imported. 

Is there i'm missing or this won't work in that way and i'm trying so solve unsolvable thing? My end goal is to have a one bundle file with all my code that i can minify.

**Comment by shellscape** [comment]
_If you are sure this is a bug, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
