### ISSUE TITLE
Get named export from folder name

### ISSUE THREAD

**Issue by sayjeyhi** [rollup/plugins#223]
I have and input like this:
```bash
input: './packages/**/index.js',
```
could I have named export for that folder name?

for example if I have `/packages/SOME_NAME/index.js'` I want to got `SOME_NAME.js` file or `SOME_NAME/index.js` file in output.

**Comment by shellscape** [comment]
_If you are sure this is a bug, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
