### ISSUE TITLE
Typescript plugin creates sourcemaps with sourcesContent null

### ISSUE THREAD

**Issue by danimoh** [rollup/plugins#260]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 4.0.0
- Rollup Version: 2.0.6
- Operating System: repl
- Node Version: 10.19.0 (repl)

### How Do We Reproduce?

https://repl.it/repls/AmpleDirtyContent (I like the name :smiley: )

### Expected Behavior

Should include original typescript source code as `sourcesContent` in sourcemaps.

### Actual Behavior

`sourcesContent` is `null` for typescript files.

**Comment by ziofat** [comment]
A workaround is add `"inlineSources": true,` to your `tsconfig.json`.

This is because typescript compiler generated sourcemap uses path instead of content of your code. It seems rollup cannot process them. `inlineSources` will force compiler to emit the source contents alongside the sourcemaps within a single map file which rollup can work with it.

**Comment by danimoh** [comment]
I think this can be closed, right?

**Comment by ziofat** [comment]
I think it can be closed now.
