### ISSUE TITLE
Is it possible to replace FOO in index.html?

### ISSUE THREAD

**Issue by chovy** [rollup/plugins#274]
Index.html isn't bundled but I want to set <title>MY_TITLE</title> from process.env.MY_TITLE.

is that possible?

**Comment by shellscape** [comment]
_If you are sure this is a bug, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by chovy** [comment]
It's not a bug its a question.

**Comment by chovy** [comment]
I was able to do it with `import replaceHtmlVars from 'rollup-plugin-replace-html-vars';`

```
    replaceHtmlVars({
      files: './public/index.html',
      from: [
        /META_TITLE/g,
        /META_DESCRIPTION/g,
        /GOOGLE_ANALYTICS/g,
        /META_DOMAIN/g,
        /META_URL/g,
        /META_TWITTER/g,
      ],
      to: [META_TITLE, META_DESCRIPTION, GOOGLE_ANALYTICS, META_DOMAIN, META_URL, META_TWITTER],
    }),
```
