### ISSUE TITLE
`@rollup/plugin-commonjs`: Can't export `require` function

### ISSUE THREAD

**Issue by fisker** [rollup/plugins#307]
- Rollup Plugin Name: 
@rollup/plugin-commonjs
- Rollup Plugin Version: 11.1.0
- Rollup Version: 2.6.1
- Operating System (or Browser): windows
- Node Version: 12

### How Do We Reproduce?

Not sure, found here https://github.com/fisker/serve-directory/pull/987/files#diff-8bd3313bc91cf9200da0f98030dfc948R14 , workaround use `global.require`

### Expected Behavior

Should works

### Actual Behavior

```text
src/core/imports.js: (14:17)
[!] Error: Unexpected token
src/core/imports.js (14:17)
12:   pkg: package_,
13:   require,
14:   ...utils,
               ^
15: })
Error: Unexpected token
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by fisker** [comment]
https://repl.it/@fisker1/ImpureEnchantedRelationalmodel-1

**Comment by danielgindi** [comment]
The plugin knows how to convert `require` into `export`, and in extreme cases where there's need for dynamic `require`, it knows how to synthesize it - where you specify upfront that you wish to do so for certain files.
The plugin has no idea what `require` is in order to export it.

What is the use case for this? (Keeping in mind that rollup is based on `import`/`export` and not `require`s)
