### ISSUE TITLE
wasm plugin shouldn’t use base64 unless a file is marked as `sync`

### ISSUE THREAD

**Issue by surma** [rollup/plugins#324]
- Rollup Plugin Name: @rollup/plugin-wasm 
- Rollup Plugin Version: 3.0.0
- Rollup Version: 2.0
- Operating System (or Browser): Chrome on MacOS
- Node Version: v12.8

### How Do We Reproduce?

https://repl.it/@surma/SaneCarelessSphere

### Expected Behavior

The .wasm file should be emitted as an asset and loaded using `fetch()` when the .wasm file is not marked as `sync.

### Actual Behavior

The .wasm file is inlined using base64, causing unnecessary file bloat.

I am opening an issue first to see if y’all would accept an PR to change the behavior of this plugin. Either me or @rreverser would be happy to whip one up :D

**Comment by shellscape** [comment]
> The .wasm file should be emitted as an asset and loaded using fetch() when the .wasm file is not marked as `sync.

That sounds like a browser environment. When working on a patch for this, it'll be important to consider non-browser environments.

**Comment by surma** [comment]
Sure, I wouldn’t break node support. Although it might be preferrable to make the target environment an option of the plugin to avoid loading unnecessary code on the web.

**Comment by RReverser** [comment]
Note that plugin runtime code already performs different actions for Node.js vs browser, so it would be quite easy to perform `fetch` + `instantiateStreaming` only in browser: https://github.com/rollup/plugins/blob/e9651fb58e01fce6af908c66d5de78542e56a41e/packages/wasm/src/index.js#L30

**Comment by manzt** [comment]
I'm curious if folks here have thoughts around best practices with shipping wasm in a library. I've found `base64` encoding to be very useful for making a wasm-based module npm-installable and easy to handle with bundlers. However, I'm not happy with using `base64` since it adds bloat and feels like a win for DX and not users ultimately.

**Comment by RReverser** [comment]
I don't really see why separate Wasm files are any harder to npm install or use in other apps?

**Comment by manzt** [comment]
Perhaps my nativity is showing here, but I'm not sure if something like `@rollup/plugin-node-resolve` can will end up adding the wasm from an npm package as an asset in the final bundle.

```javascript
// some-npm-module.js
async function init() {
  const { instance }  = await WebAssembly.instantiateStreaming(fetch('simple.wasm'), importObject)
  return instance 
}
export init;
```

```javascript
// my-lib.js
import { init } from 'some-npm-module';
init();
```
In my experience, the wasm asset doesn't end up in the final bundle when using `@rollup/plugin-node-resolve`. Am I missing something? (likely).

**Comment by RReverser** [comment]
I'm a bit confused too, to be honest. What is the sample source here?

This issue is about the [Rollup Wasm plugin](https://github.com/rollup/plugins/tree/e9651fb58e01fce6af908c66d5de78542e56a41e/packages/wasm) that handles things like `import wasm from './sample.wasm';`, but I don't see that in either of samples above?

The idea is that Rollup will use `emitFile` like it does for other binary assets, which takes care of emitting them into a preconfigured folder (either alongside JS or elsewhere), then resolving URLs to the emitted assets, and using either `fetch` in the browser or `fs` APIs in Node to load it asynchronously.

Not sure if it makes sense? 😀

**Comment by manzt** [comment]
Makes total sense! Thanks for the detailed description. I was trying to (unsuccessfully) make the point that as a _consumer_ of a library bundled with `@rollup/plugin-wasm`, it is convenient to have the binary `base64` encoded as I'm not sure how something like `@rollup/plugin-node-resolve` handles including binary assests in an npm dependency.

**Comment by RReverser** [comment]
Ah I see, thanks for clarification. I *think* it should work, but I have no idea how Rollup resolves references to `emitFile`-produced binaries in Node.js.

**Comment by bminixhofer** [comment]
Hi, is there still interest to implement this @RReverser @surma ?

I would need it for https://github.com/bminixhofer/tractjs/issues/12. I see a 36% size increase when inlining the WASM. I think *anyone* who develops for the browser using WASM and Rollup needs this option. A > 30% size increase is rarely acceptable.

I could give this a go if you are not planning to implement it anymore, but I currently don't know the internals of Rollup so I would be grateful if you could do it 😃

**Comment by RReverser** [comment]
This is absolutely still an important issue that shouldn't have been closed as stale. If you can implement it, give it a go!

**Comment by shellscape** [comment]
I'm willing to reopen this if someone opens a PR to address it. It previously went over two months without anyone giving it attention, which is why it was closed automatically by the bot. We simply don't have the manpower to address all issues, so we welcome community contribution. If anyone would like to step up as lead for the wasm plugin we'd also welcome that.

**Comment by bminixhofer** [comment]
Understandable. I'll try implementing this and open a PR if I get it to work.

**Comment by RReverser** [comment]
> We simply don't have the manpower to address all issues, so we welcome community contribution.

All the more reason to keep issues open, so that community could easily see what work is needed or which bugs are known, and help to address them.

**Comment by shellscape** [comment]
> All the more reason to keep issues open, so that community could easily see what work is needed or which bugs are known, and help to address them

We disagree there. That methodology was tried and failed in both the previously existing individual plugin repos and the main rollup repo. What we ended up with was a 4 year backlog of issues that no one had touched in eons, some of which were out of sync with current versions. The optics of a project with pages upon pages of open issues is discouraging to potential contributors and users alike. You're of course welcome to disagree, but we've been at this a _long_ time, and that's how we've chosen to manage the issues.

**Comment by shellscape** [comment]
Big thanks to @bminixhofer for stepping up with a PR
