### ISSUE TITLE
regeneratorRuntime error with 'external' helpers

### ISSUE THREAD

**Issue by cutterbl** [rollup/plugins#356]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.0.0
- Rollup Version: 2.7.5
- Operating System (or Browser): Mac
- Node Version: 10.14.0

I have the following config:

```js
import path from 'path';
import babel from '@rollup/plugin-babel';
import clear from 'rollup-plugin-clear';
import { eslint } from 'rollup-plugin-eslint';
import cleanup from 'rollup-plugin-cleanup';
import pkg from '../package.json';

export default [
  {
    input: path.join(__dirname, '../src/index.js'),
    output: [
      {
        file: pkg.module,
        format: 'es',
        sourcemap: true,
        exports: 'named',
      },
    ],
    plugins: [
      clear({
        targets: [path.join(__dirname, '../dist')],
        watch: true,
      }),
      eslint(),
      babel({
        babelHelpers: 'external',
      }),
      cleanup(),
    ],
  },
];
```

Along with the following `babel.config.json` file

```
{
  "presets": ["@babel/preset-env"],
  "plugins": ["@babel/external-helpers"]
}
```

I have a babel external helpers file I load in the browser. When I include my built file (which built without error), I get the following console error:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

Inspecting my built file, I find several references to the `reneratorRuntime`.

Did I miss something?

### Expected Behavior

Built file would allow for using the external babel helpers

### Actual Behavior

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

[Here is the repo](https://github.com/cutterbl/soundtouchjs-audio-worklet) where I'm trying to get this working.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by cutterbl** [comment]
I provided a repo link. Not enough?

**Comment by shellscape** [comment]
Sorry, sometimes my script doesn't pick that up.

**Comment by JMarkoski** [comment]
When transpiling your code with `@babel/preset-env` and you don't specify targets, the preset transpiles everything down to `es5`. Now, when using `async` functions, the transpiled code depends on generators, so it references the regenerator runtime globally and it should be available before your code uses the transpiled `async` functions or generators. You can manually include it like this `import 'regenerator-runtime/runtime` at the top of the entry file. This is globally pollutable, and makes the runtime available to your code as `window.reneratorRuntime`. Note that, using `@babel/preset-env` without `useBuiltIns`, won't include any polyfills for your code **even** if they are required in order your code to function on older browsers. The problem here with setting `useBuiltIns` to `usage` is that that will inline the babel helpers where needed, but you already externalized them and use them from the global `babelHelpers`. Another option that is left with this config is to use the `@babel/transform-runtime` plugin and turn off the `helpers` option, and turn on only the `regenerator` option, together with `@babel/runtime` as dependency, but this option suffers from that that `@babel/transform-runtime` plugin doesn't accept targets, so it will polyfill every feature by default. The only sensible option that is left with the `external` config is to include it manually at the top of the entry point file.
