### ISSUE TITLE
[node-resolve] Support conditional exports defined in package.json

### ISSUE THREAD

**Issue by kripod** [rollup/plugins#362]
- Rollup Plugin Name: @rollup/plugin-node-resolve
- Rollup Plugin Version: 7.1.3

### Feature Use Case

Recently, [conditional exports](https://nodejs.org/api/esm.html#esm_conditional_exports) have been introduced into the Node module resolution algorithm. Modern packages may rely upon them more and more.

### Feature Proposal

When the field `type` is set to `module` inside a `package.json` file, prefer `exports.{import,require,node,default}` instead of the current `mainFields`.

**Comment by manzt** [comment]
Second this. Node Package Exports allows for the declaration of additional exports as well:
```
{
  "name": "myLib",
  "type": "module",
  "main": "dist/index.js",
  "exports": {
      ".": "dist/index.js",
      "./submodule": "dist/some-nested-path/submodule.js"
  }
}
```

Usage in Node 14
```javascript
import mainModule from 'myLib';
import subModule from 'myLib/submodule';
```

**Comment by brettz9** [comment]
`type: "module"` is only needed to get "js" treated as "mjs"--but without the `type`, one can still use ".mjs"--as well as use `exports`. So I'd hope `exports` could be checked regardless of `type`.

**Comment by brettz9** [comment]
Though [the docs](https://nodejs.org/api/esm.html) do mention a few types and speak about possible future restrictions on these values:

> Other conditions such as "browser", "electron", "deno", "react-native", etc. are ignored by Node.js but may be used by other runtimes or tools. Further restrictions, definitions or guidance on condition names may be provided in the future.

...I wonder if Rollup plugins--one of such mentioned tools--might pioneer supporting use not only of "browser" but of "browser-esm" or such. Too frequently I encounter the notion that packages shouldn't ship prebuilt browser ESM because:

1. They wrongly think that the extra HTTP requests will become unduly burdensome, despite the fact that some prefer ESM for light demos or local use, allowing for easier debugging and lack of build steps.
2. Some may wrongly think apps will always want to take pains to support older non-ESM browsers (even when that means non-modular code with global script dependencies polluting their HTML).
3. They think browsers shouldn't directly load `node_modules` files because of the potential for nested `node_modules`--even though it will usually be app demos which may wish to directly use ESM in the browser, and for them, this is generally not a problem (and with import maps, it should [become even less of a problem](https://github.com/WICG/import-maps/issues/126)).
4. They wrongly think their package consumers don't mind following their extra instructions (or diving into their source) to figure out which plugins and config to add to get their code working. Responsible projects don't see it as binaries vs. source, but provide both (unless they have reason for concern with large package sizes when their dependencies are very large).

Also, I think it would be wise to settled on "browser-uncompiled", "node-uncompiled" too, to set aside special fields for uncompiled source since many projects seem to wish to insist on pointing `module` to non-transpiled code and forcing their consumers to do their own transpiling; this despite the fact that the [Rollup wiki `module` docs](https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features) suggest pre-transpiling. But if there were a reserved "uncompiled" field, it could encourage use of both fields (since projects do have some valid reasons for shipping untranspiled code (allowing consumers not to be tied to the bundled version, and perhaps file size, etc.)).

**Comment by xiaoxiangmoe** [comment]
Also, should we use [Nested conditions](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_nested_conditions) as below?

```json
{
  "main": "./main.js",
  "exports": {
    "browser": "./feature-browser.mjs",
    "node": {
      "import": "./feature-node.mjs",
      "require": "./feature-node.cjs"
    }
  }
}
```

**Comment by lukastaegert** [comment]
As it turns out after some discussion, Webpack will be adding a `module` condition (that can be combined with `browser`), see here https://github.com/webpack/webpack/issues/11014#issuecomment-643256943 and in the linked specs. I think this addresses at least some of @brettz9 's core concerns and Rollup will likely support this out-of-the-box as well, though there are still discussions. In the end of course we will probably build a solution where a user will also be able to set their own set of conditions, e.g. "node" + "module" etc. both globally and for individual packages.

Nevertheless, here is another pattern that also addresses the main browser concern, but it is a slight variation of what @xiaoxiangmoe mentions:

```json
{
  "main": "./main.js",
  "exports": {
    "node": {
      "import": "./feature-node.mjs",
      "require": "./feature-node.cjs"
    },
    "default": "./feature-browser.mjs"
  }
}
```

Of course this only makes sense if the library does not specifically depend on browser globals. Then the idea is that ALL non-node environments basically only understand and like ESM—which is a prudent assumption as ESM is the native module format of JavaScript.

Once we have `exports` support in `node-resolve`, the pattern I mentioned will be working without further configuration by `node-resolve` while the previous will not because out of the box, `node-resolve` will likely set neither the `browser` nor the `node` condition.

**Comment by LarsDenBakker** [comment]
Not stale :)

**Comment by 75lb** [comment]
this issue is a blocker for me.. I use the `exports` package.json property everywhere now (there's no reason not to - it has replaced the `main` package.json property). 

I have a package which maps `./v3` to `/lib/v3.mjs` like this: 

```
"exports": {
  "./v3": "./lib/v3.mjs"
},
```

However, i'm blocked from consuming this package using rollup since rollup doesn't support `exports` and the package does not export the `/lib` folder, so a workaround fix of changing the `import` statement to the below fails to run in Node: 

```js
// this fails since the lib folder is not exported from the package
import ApiV3 from 'my-package/lib/v3.mjs`
```

Watching this thread for updates...

**Comment by brettz9** [comment]
@75lb : That should be a bug with that package then. (With the exception that if the project's `package.json` uses `files` to whitelist allowable files, and does not include `lib` in the project, and your dependency chain is not targeting a version on npm but is instead targeting a GitHub URL like: `"example": "https://github.com/example/example#master"`, then you will instead need to fork the project, remove any exclusion of `lib` from `.gitignore` and add the `lib` files to the repo, and target your fork like `"example": "https://github.com/<me>/example#branch-with-the-lib-files"`--or yourself repeat their build process, something I wouldn't recommend.)

Rollup only works with interpreting `exports` in package.json if you use the @rollup/plugin-node-resolve plugin (since main Rollup is not aware of Node-style importing/exporting by default).

By, the way, the new equivalent for `exports` of the `mainFields` referenced in this issue (mentioned before it was implemented is `exportFields`) as per https://github.com/rollup/plugins/tree/master/packages/node-resolve#exportconditions . One can use that to control priority of which `exports` gets applied, though in your case, with there being only one, it is not relevant; I mention, however, given the nature of this particular issue, and for others who might discover this issue.

**Comment by 75lb** [comment]
@brettz9 I disagree that it's a bug.. The fundamental purpose of the `exports` object is to decouple a module ID naming convention (e.g. `my-package/v3`) from the internal implementation specifics of the package. It enables the package author to completely change the internal package structure without breaking the public-facing API, it's a great feature. 

[Conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports) (the original issue topic) are fundamentally required to make a ESM package also support CommonJS requires. You can't `require` a ESM file from a CommonJS file, that's why conditional exports were created.

**Comment by brettz9** [comment]
@75lb : My apologies, it looks like I misunderstood.

**Comment by Mwni** [comment]
So is this implemented? Setting `exportConditions: ['node']` as stated in the readme should resolve the `exports` of the `package.json`, but it doesn't. Am I doing it wrong?

**Comment by guybedford** [comment]
@Mwni this should be fully supported now, if it's not working for you please post a new issue with the exact steps to replicate.

**Comment by Mwni** [comment]
@guybedford Thanks, will do.
