### ISSUE TITLE
[@rollup/plugin-run] fork cwd and output path

### ISSUE THREAD

**Issue by takase1121** [rollup/plugins#364]
I configured my rollup to generate output with this structure:
```
 dist
├── public
│   ├── client.js
│   └── index.html
└── server.js
```
the `client` folder contains static files that I want to serve. I use [sirv](https://github.com/lukeed/sirv/tree/master/packages/sirv) to serve it
. 
I put `public` and it is automatically resolved against `process.cwd()`. This is a problem since apparently the script is running at the project base directory (where `package.json` resides). 

I tried to use `cwd: './dist'` to make sure it ran at `./dist`, but this causes the plugin to resolve my output file as `./dist/dist/server.js`. How do I solve this?

**Comment by takase1121** [comment]
I currently use the plugin with `env: { DIST_DIR: './dist/' }` and setup corresponding logic in my server to use correct file path. Its working but I think it (probably) wasn't the desired behavior.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
