### ISSUE TITLE
Generating d.ts files in TypeScript projects

### ISSUE THREAD

**Issue by mjackson** [rollup/plugins#394]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 4.1.1

Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

It isn't clear to me how to get the typescript plugin to generate d.ts files in the output. I've tried adding `{ declaration: true, declarationDir: 'dist' }` to the plugin config and `output.dir` to the Rollup config, but it just fails silently without creating any d.ts files.

I made a branch here with my progress so far: https://github.com/ReactTraining/react-router/tree/dev-rollup-ts

### Your Proposal for Changes

I'd like to see a clear example in the typescript plugin's README file about how to generate d.ts files in the output.

**Comment by leecade** [comment]
big problem here

**Comment by shellscape** [comment]
@leecade that's why we labeled it `critical`. please refrain from posting _"me too"_ type replies. It only adds extra noise.

**Comment by egoist** [comment]
Maybe give https://github.com/Swatinem/rollup-plugin-dts a try? It also bundles your d.ts files

**Comment by mjackson** [comment]
@egoist I'm currently using rollup-plugin-typescript2 to generate my d.ts files, so I've already got *something* working. This issue is more about getting support for generating d.ts files in the official plugin for typescript.

**Comment by axelekwall** [comment]
Any updates on the progress on this issue? I have some time free and would like this fixed, is there any way I can help? @shellscape  @NotWoods

**Comment by calebdwilliams** [comment]
If it helps declaration files seem to work just fine when using `outDir`, but fail silently when using `declarationDir`.

**Comment by andongxiao** [comment]
I tried to add `rootDir` field in typescript plugin config and it works

**Comment by rikoe** [comment]
Despite being marked as critical, this issue has been open since May last year! Any update on how to fix or work around this? I have tried various combinations of tips people provide here and on other issue threads, like specifying `outDir` and not `declarationDir`, or specifying `declarationDir` in rollup config and not in tsconfig, but it all seems like cargo culting to me.

Emitting type declaration files just doesn't seem to work on my library build, whatever combination of config I use.

I am now being forced to switch to `rollup-plugin-typescript2`, which I didn't really want to do (I would like to use the official plugin).

Happy to do a PR to try and address this, if someone can point me in the right direction...

**Comment by nandi95** [comment]
@rikoe 
I got it to emit the declarations with the official typescript plugin:
I had to pass it the path to my `tsconfig.json` like so:
```js
typescript({ tsconfig: './tsconfig.json' }),
```

It seems it isn't using it by default?

**Comment by shellscape** [comment]
@rikoe Despite being open since May of last year, no one in the community has stepped up to help us resolve it, and unfortunately none of the current maintainers get paid to resolve issues! In all seriousness, we do what we can, and starting issues off with language like that is a bummer to folks who donate their time to the project. Please rethink your approach next time.

The approach by @nandi95 is correct, in that the default configuration internally is not configured to emit declarations. There may be an opportunity to improve the README for the plugin, and we'd welcome any suggested updates in a PR to assist users. However, it appears that there's still a bug in that approach. To resolve that bug, a new issue should be opened with a reproduction for that particular case.

I can leave this open if someone would like to submit a PR with a documentation update.

**Comment by shellscape** [comment]
For onlookers, I have a PR open in #791 to reorganize the tests for declarations to make them more discoverable and easier to read through. It looks like we've had declaration support for some time since this issue was created. The tests cover both using `tsconfig.json` and passing options directly. The reproduction used in the issue is on `^4.1.1` and we're currently at `^8.1.1`. It also looks like that may be some edge cases that aren't handled, based on the comments here. Given that we have some good tests around this and can verify that declarations are being generated, I'm going to close this one, as additional documentation isn't needed (it should work as expected).

For anyone working in a scenario where this _isn't_ working as expected, please open new issues with your reproductions, so we can tackle each edge case on a case-by-case basis and give them the attention each needs.

**Comment by felixapitzsch** [comment]
> @rikoe
> I got it to emit the declarations with the official typescript plugin:
> I had to pass it the path to my `tsconfig.json` like so:
> 
> ```js
> typescript({ tsconfig: './tsconfig.json' }),
> ```
Thanks for the hint. This was the change that finally made it work for me, too! However, I had to specify the **./** prefix. Before reading your comment, I tried `typescript({ tsconfig: 'tsconfig.json' }),` multiple times _without this prefix_ and that _did not work_ for me.

**Comment by avalenti89** [comment]
> > @rikoe
> > I got it to emit the declarations with the official typescript plugin:
> > I had to pass it the path to my `tsconfig.json` like so:
> > ```js
> > typescript({ tsconfig: './tsconfig.json' }),
> > ```
> 
> Thanks for the hint. This was the change that finally made it work for me, too! However, I had to specify the **./** prefix. Before reading your comment, I tried `typescript({ tsconfig: 'tsconfig.json' }),` multiple times _without this prefix_ and that _did not work_ for me.

Not for me. I tried with **rootDir**, **outDir**, **declarationDir**, with and without **./**. No working configuration...

**Comment by jpoehnelt** [comment]
for those running into this, be aware of https://github.com/rollup/plugins/issues/978

**Comment by rikkit** [comment]
Because I've spent too much time on this today (the key for me is that the tsconfig.json wasn't auto loaded by `@rollup/plugin-typescript`!! I'm sure the docs say it is), so for whoever stumbles onto this from Google here is a working config for Rollup 2.3 and TypeScript 4.6 with sourcemaps and a single definition file output: https://gist.github.com/rikkit/b636076740dfaa864ce9ee8ae389b81c

**Comment by mindplay-dk** [comment]
> Because I've spent too much time on this today (the key for me is that the tsconfig.json wasn't auto loaded by `@rollup/plugin-typescript`!! I'm sure the docs say it is), so for whoever stumbles onto this from Google here is a working config for Rollup 2.3 and TypeScript 4.6 with sourcemaps and a single definition file output: https://gist.github.com/rikkit/b636076740dfaa864ce9ee8ae389b81c

`@rollup/plugin-typescript-dts` appears to be the secret sauce here.

Perhaps the documentation should mention that? I don't think anyone wants to ship dozens of `.d.ts` files, and apparently that's the limitation with the official plugin?

Also, why does `{ tsconfig: './tsconfig.json' }` somehow trigger some magic that makes `.d.ts` output work at all? The plugin appears to respect my compiler settings either way - except, for some reason, *not* the `declaration` and `declarationDir` settings?

It's a very confusing and frustrating experience. RollUp is generally very library-oriented, and it's very unlikely anyone would want to ship a TS library without types, isn't it? So the default settings don't make a lot of sense, the documentation section isn't very helpful, and the error message you get isn't very helpful either:

    [!] (plugin typescript) Error: @rollup/plugin-typescript: You are using one of Typescript's compiler options 'declaration', 'declarationMap' or 'composite'. In this case 'outDir' or 'declarationDir' must be specified to generate declaration files.

Doing exactly what the error message says doesn't produce any result at all - and once you figure out that the `tsconfig` plugin option is required, that doesn't produce the result most people need either.

It looks like your options right now are:

1. Workarounds as documented, putting up with shipping a bunch of `.d.ts` files.
2. Build `.d.ts` files using `tsc` ahead of time, bundle them with `@rollup/plugin-typescript-dts`.
3. Switch to `rollup-plugin-typescript2` maybe? (it's not clear to me if people in this thread are switching because they can't get `.d.ts` output to work at all, or whether this plugin is capable of producing a single `.d.ts` file - or if `@rollup/plugin-typescript-dts` in a separate build is still required?)

**Comment by shellscape** [comment]
Make sure not to confuse the `@rollup` with a `rollup-` prefix, or you'll be wondering why the NPM registry is returning 404s :)

**Comment by rondonjon** [comment]
Thanks, @mindplay-dk, for summarizing the situation and the available options.

Yesterday I stumbled upon [this discussion](https://github.com/timocov/dts-bundle-generator/discussions/68#discussioncomment-240067) around [dts-bundle-generator](https://github.com/timocov/dts-bundle-generator) and tried it out, and it is working quite well for me.

Since dts-bundle-generator is published as a CLI app, I have wrapped it as a rollup plugin [here](https://www.npmjs.com/package/rollup-plugin-dts-bundle-generator).

**Comment by mindplay-dk** [comment]
Personally, I switched to Parcel where this "just works" - you can see my setup [here](https://github.com/mindplay-dk/inertion) if that's helpful.

**Comment by f-lawe** [comment]
I recently had the same need with Vite, and noticed that [rollup-plugin-dts-bundle-generator](https://www.npmjs.com/package/rollup-plugin-dts-bundle-generator) does not seem to be maintained any more. I migrated everything to unplugin, so in case some here needs an updated version: [unplugin-dts-bundle-generator](https://github.com/f-lawe/unplugin-dts-bundle-generator).

**Comment by mindplay-dk** [comment]
Years later, and I've simply stopped bundling .d.ts files.

Just ship them as they are - TypeScript works fine with any number of .d.ts files. 🙂
