### ISSUE TITLE
SyntaxError: The requested module '@rollup/pluginutils' does not provide an export named 'createFilter'

### ISSUE THREAD

**Issue by AlttiRi** [rollup/plugins#401]
Rollup Plugin Name: ---
Rollup Plugin Version: 3.0.10
Rollup Version: ---
Operating System (or Browser): Windows
Node Version: 14.2.0

I get the error when some plugin uses `pluginutils`:

```
import { createFilter } from "@rollup/pluginutils";
         ^^^^^^^^^^^^
SyntaxError: The requested module '@rollup/pluginutils' does not provide an export named 'createFilter'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

### How Do We Reproduce?
Create the project from 2 files:

_package.json_
```json
{
  "name": "example",
  "version": "1.0.0",
  "type": "module",
  "devDependencies": {
    "@rollup/pluginutils": "3.0.10"
  }
}
```
_build.js_
```js
import {createFilter} from "@rollup/pluginutils";
```

Run `build.js` 

### Expected Behavior
No errors.

### Actual Behavior
The error that is listed above.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by AlttiRi** [comment]
> It also pretty clearly does export that method

I see. But I get the error when I use `rollup-plugin-sourcemaps` anyway.

**Comment by shellscape** [comment]
That plugin doesn't exist in this repo.
