### ISSUE TITLE
Is there a plugin to load fully qualified module URLs?

### ISSUE THREAD

**Issue by mreinstein** [rollup/plugins#405]
I want to start moving towards standardized browser imports in my code. For example:

```javascript
import * as vec2 from 'https://cdn.jsdelivr.net/npm/gl-matrix@3.3.0/esm/vec2.js'
```

This totally works in modern browsers today, and I want to be able to generate rollup bundles that reference these urls (able to fetch them over the network and bundle em' in)

Is there already a plugin for this or is it net new?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

Also look up rollup/awesome
