### ISSUE TITLE
Regression @rollup/plugin-commonjs v13.0.0

### ISSUE THREAD

**Issue by MatthiasKainer** [rollup/plugins#454]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: v13.0.0
- Rollup Version: 1.32.1
- Operating System (or Browser): any
- Node Version: any

### How Do We Reproduce?

https://repl.it/repls/PhonyUsefulNanotechnology#output/bundle.js

Have a file like 
```js
import {LitElement, html} from "lit-element"
import { useState } from "lit-element-state-decoupler";
import {useOnce} from "lit-element-effect";

export class Element extends LitElement {
  render() {
    const {getState, publish} = useState(this, false)
    useOnce(this, () => publish(true))

    return html`<div>Called: ${getState()}<div>`
  }
}
```

### Expected Behavior

The imports are resolved correctly. In the bundle that would create a result: 

```js
class Element extends LitElement {
  render() {
    const {getState, publish} = index.useState(this, false);
    index$1.useOnce(this, () => publish(true));

    return html`<div>Called: ${getState()}<div>`
  }
}

```

(Note the `index$1` on `useOnce`)

### Actual Behavior

`useOnce` is retrieved from `index`, which obviously fails:

```js
class Element extends LitElement {
  render() {
    const {getState, publish} = index.useState(this, false);
    index.useOnce(this, () => publish(true));

    return html`<div>Called: ${getState()}<div>`
  }
}

```

### Workaround

Use version 12.0.0 of @rollup/plugin-commonjs instead of v13.0.0

**Comment by vladshcherbin** [comment]
I've got same thing with another library, also with `index` near this line:

```js
console.log(1, lib)

var index = /*@__PURE__*/unwrapExports(lib);

console.log(2, index)
```

I believe exports are unwrapped incorrectly, here is result:

![image](https://user-images.githubusercontent.com/6711845/85238164-b10deb80-b434-11ea-9d0c-b7d9a1851916.png)

From [source code](https://github.com/rollup/plugins/blob/commonjs-v13.0.0/packages/commonjs/src/helpers.js#L26-L28) function checks for `default` export and uses it, however object can have other keys which will be removed.

Bundling results in an application error shown above. Workaround is to use 12.0.0.

Will be probably fixed with https://github.com/rollup/plugins/pull/465

**Comment by lukastaegert** [comment]
I started #481 to move all interop issues including this one forward.

**Comment by lukastaegert** [comment]
I can confirm that #501 solves this issue.
