### ISSUE TITLE
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by X37ddV** [rollup/plugins#464]
- Rollup Plugin Name: @rollup/plugin-sucrase
- Rollup Plugin Version: 3.0.2

```javascript
class App {

  public func<
    T extends 
    | number
  >(...name: string[]): T {
    return 1 as any
  }
}

export default App
```
```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
5:     T extends 
6:     | number
7:   >(...name: string[]): T {
   ^
8:     return 1 as any
9:   }
```

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
