### ISSUE TITLE
plugin-babel/package.json is missing 'type':'module'

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/plugins#470]
I use NodeJS 14 and the rollup API.  My package.json contains `'type':'module'`.  I write `'import {babel} from '@rollup/plugin-babel'`  I expect, that NodeJS will load plugin-babel's `'module':'dist/index.es.js'`.  But it is not loaded.  NodeJS says instead that `@rollup/plugin-babel` is expected to be of type CommonJS, which does not support named exports.

• Include in babel/package.json `'type':'module'`.

See also https://github.com/nodejs/node/issues/34027.

**Comment by dilyanpalauzov** [comment]
Or insert "exports" section in `package.json` as `rollup-plugin-terser` [does](https://github.com/TrySound/rollup-plugin-terser/blob/master/package.json#L8).

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
