### ISSUE TITLE
typescript changes taken into account only after 2nd rebuild in watch mode

### ISSUE THREAD

**Issue by cbxp** [rollup/plugins#493]
"@rollup/plugin-typescript": "^4.1.2"
"rollup": "^2.21.0"

We have svelte + typescript project.

When we change any plain typescript file, the watch triggers rebuild, but old version of the code still runs until you rebuild again.

We will upload a project that you can play with.

Steps to reproduce:
* Run `npm run watch`
* Change `index.ts`
* Check that rebuilt `build/index.js` still has old code
* Change `index.ts` again
* `build/index.js` will contain code of previous change

**Comment by cbxp** [comment]
[tsbug.zip](https://github.com/rollup/plugins/files/4895712/tsbug.zip)

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

**Comment by angryziber** [comment]
@shellscape really? We have created a minimal project that shows the issue clearly. You need to unzip the attached above tsbug.zip and run watch on it. As simple as that. Not sure if this can be reproduced in any web-based REPL - you need to watch FS changes here.

Basically, the plugin is not very usable right now for development, I would say, broken. First the memory leak issue and now this. Please take the issue seriously. We had to switch to another rollup typescript plugin that works for now. The issue is just there - you don't have to do anything special to reproduce - just unzip our project or create a new one. If this issue is not fixed, the plugin should be better deleted to avoid confusion as there are working alternatives, despite this one seems to be an "official" one.

**Comment by shellscape** [comment]
we ask that all users, including maintainers, adhere to the same issue templates and provide the same information as everyone else. you have chosen not to, therefore we will not be triaging your issue. I wish you luck with the alternate plugin you have chosen.
