### ISSUE TITLE
try-catch require() not supported

### ISSUE THREAD

**Issue by staadecker** [rollup/plugins#496]
- Rollup Plugin Name: common-js
- Rollup Plugin Version: 13.0.1
- Rollup Version: 2.21.0
- Operating System (or Browser): Windows 10 / Node
- Node Version: 10.16.3
- Link to reproduction : https://github.com/staadecker/rollup-bug-reproduce

### Expected Behavior

```
let someOptionalDependency;

try {
  someOptionalDependency = require("optional-dep")
} catch (e) {
}

if (someOptionalDependency) {
  console.log("Do something with this dependency");
} else{
  console.log("Do something else since the dependency is unavailable")
}
```
This code should not throw an error when bundled with rollup and the CommonJS plugin.

### Actual Behavior

Rollup bundles the code to `var optionalDep = _interopDefault(require('optional-dep'));`

This line throws `Error: Cannot find module 'optional-dep'`.

### Steps to reproduce

1. Clone https://github.com/staadecker/rollup-bug-reproduce

2. Run `yarn`.

3. Run `yarn start`. The code runs fine.

4. Run `yarn build-and-run`. The code crashes.

### Additional Information

See the following issues,

[This issue](https://github.com/rollup/rollup/issues/1385) is the same as the one I describe except for `import` rather than `require`. That issue is resolved.

[This other issue](https://github.com/rollup/rollup-plugin-commonjs/issues/89) is the same as the one I describe however was incorrectly marked as a duplicate of the first.

### Impact

I believe this issue has caused [this one](https://github.com/Automattic/mongoose/issues/8602) where a peer dependency which is normally optional causes the bundle to crash.

I've also ran into this issue on some work where I was using the try-catch require. This seems to be common practice and I'm surprised rollup doesn't handle this case.

**Comment by shellscape** [comment]
Thanks for opening an issue. We'd love to have contribution on this so please do consider opening a PR.

**Comment by staadecker** [comment]
I don't think I have time / expertise to open a PR right now, so if anyone wants to go ahead.

**Comment by limitlessloop** [comment]
It's taken me an extremely long time to narrow the issue down to this, but I believe this is affecting something I'm trying to do. I'm trying to check if a user has a config file in their current working directory. But unfortunately, I can't do this because Rollup complains about not being able to resolve the file. Normally I would use a catch block to optionally check for a file.

In my particular case, there is no workaround for this apart from insisting that the user has the file in their directory, if it wasn't for the fact this is for a Figma plugin where the code exists in a sandboxed environment, it wouldn't be a problem, but alas it is.
