### ISSUE TITLE
unwrapExports was removed

### ISSUE THREAD

**Issue by victoriafrench** [rollup/plugins#497]
@FredKSchott 

The commit 7e75713 `fix(commonjs): Support __esModule packages with a default export (#465)`, `unwrapExports` was removed entirely. No other information was provided on this. 

How are we to fix our builds that will not work now that this has been removed? An example is importing `redux-subscriber`. This latest release results in the import being undefined (uses the default import). We have a few others in the app that are transpiling to the same error. We had to revert to 13.0.0.

Any help would be appreciated.

**Comment by victoriafrench** [comment]
referencing PR #465

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by victoriafrench** [comment]
let me get this straight, you all violate semver and release a breaking change as a patch, with absolutely no tests cases, documentation changes, or release notes... and I get the snarky reply on this.

**Comment by shellscape** [comment]
You willfully disregarded instructions for new issues. The onus for that is on you unfortunately. We ask the same of all who open issues and pull requests on this repo, including maintainers and owners.

**Comment by lukastaegert** [comment]
Still I want to give some perspective to the original decision: 13.0.0 was broken for a lot of packages due to when and how unwrapExports was applied. The effect was that no named exports were working for many packages that were transpiled from an ES module. A proper solution is in preparation but we needed to make a call, and in this case we decided to fix it so that it worked at least for most cases, the only exception being when a transpiled ES module actually puts its default export on the `default` property. I am sorry this is not working for these specific packages, the tracking issue is #481.
