### ISSUE TITLE
[strip] replace prototype methods with empty ones

### ISSUE THREAD

**Issue by yairEO** [rollup/plugins#508]
Unclear if `functions` option removes the function declaration itself or just the function calls (the invocations to that function). 

https://github.com/rollup/plugins/tree/master/packages/strip#functions

---
![image](https://user-images.githubusercontent.com/845031/88479299-b344f780-cf56-11ea-958d-d7e3645f3d7c.png)

---
I am looking for a way to stip away whole methods of a my prototyped function and it seems to do nothing.

## Example code

```
function Foo(){
}

Foo.prototype = {
  bar(){ // <-- want to remove the whole method "bar" and replace with with an empty one 
     ...
     tons of code
     ...
  }  
}
```

My Rollup plugins config:
```
[
    strip({
      functions: ['Foo.bar']  // also tried Foo.prototype.bar
    }),
    babel({...babelConfig, babelHelpers: 'bundled'}),
    ...morePlugins
]
```

I'm using `Rollup` version `2.22.1` and `Node` version `11.13.0` and `strip` plugin version `2.0.0`

Is my goal achievable using this plugin?

Thanks!

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
