### ISSUE TITLE
Fix the website links for all rollup-plugin-something

### ISSUE THREAD

**Issue by aminya** [rollup/plugins#516]
Now when I search for some rollup plugin in Google or Bing, the first search result is the archived Github repository. 

![image](https://user-images.githubusercontent.com/16418197/88814417-ad7e2a80-d17f-11ea-9676-fb15d60b4e41.png)

The link points to the root of this repository instead of the actual sub-repository (https://github.com/rollup/plugins/blob/master/packages/wasm). 

![image](https://user-images.githubusercontent.com/16418197/88814432-b4a53880-d17f-11ea-93af-9fc7e59993ef.png)

I believe these links should be fixed so they point to the sub repository, so we can quickly go and read the Readme without going through a couple of links for no reason.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by aminya** [comment]
@shellscape You're welcome. Unfortunately, you've missed all the different topics that humans (not robots) can talk about in your issue templates. Give me a link that is about GitHub website link issues, and I will copy paste my issue there.

**Comment by shellscape** [comment]
Our issue templates are non-optional, and that's spelled out quite plainly in them all. The onus for your failure, or unwillingness, to use them is unfortunately upon you. Some very light reading would have revealed that the `Modification` template would have fit this.

We're also not going to worry about google results - they're algorithm is their own and it doesn't affect us. If I search NPM for `rollup wasm` the first link points to the correct module and repo https://www.npmjs.com/search?q=rollup%20wasm. Choose a better search method.
