### ISSUE TITLE
TypeScript plugin crashes when it encounters syntax error

### ISSUE THREAD

**Issue by benmccann** [rollup/plugins#542]
- Rollup Plugin Name: TypeScript
- Rollup Plugin Version: 4.x and 5.x
- Rollup Version: Latest
- Operating System (or Browser): Ubuntu
- Node Version: 12
- Link to reproduction: https://github.com/sveltejs/template

### Expected Behavior

If a syntax error is encountered when in watch mode, Rollup should continue watching for changes

### Actual Behavior

The plugin crashes

### Additional Information

To reproduce, do the following:
```
git clone git@github.com:sveltejs/template.git
node scripts/setupTypeScript.js
npm install
npm run dev
```

Type random letters in random places in `src/main.ts`

**Comment by shellscape** [comment]
Thanks for the issue, but did you try searching before opening this? It's a duplicate of #418, #429, #442, #478 and related to #272 (open).

That's also not a valid minimal reproduction. _  2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions)._ The article linked to there was written by our very own, @Rich-Harris.

Because this is a duplicate I'll let you choose which older issue best represents your case, and suggest which should be reopened (or if #272 should be expanded upon). Once you've chosen please comment on that issue and close this one.

**Comment by benmccann** [comment]
I did see https://github.com/rollup/plugins/issues/272. However, I did not set `noEmitOnError` in my project and looked it up and saw that [the default for `noEmitOnError` is false](https://www.typescriptlang.org/docs/handbook/compiler-options.html), so the description of #272 didn't seem to fit my issue since I assumed I already had `{ noEmitOnError: false }`. I see now that the TypeScript plugin sets a different default, but that it's extremely unintuitive and unexpected to me that it would be overwriting the options I provided (and even more so that it would do so in a way that breaks the plugin). Also, the symptoms in #272 are also not well explained ("breaks" in what way?) nor was there any explanation as to why that flag is required or has an effect. 

I didn't try searching closed issues since this is an issue that's currently present. Some of them don't actually seem related. E.g. I was actually the one that filed https://github.com/rollup/plugins/issues/478 and am quite certain that's a different issue.

I'll close this in favor of #272
