### ISSUE TITLE
How to track down "Dynamic requires are not currently supported by rollup-plugin-commonjs" error?

### ISSUE THREAD

**Issue by ceremcem** [rollup/plugins#562]
I'm getting "Dynamic requires are not currently supported by rollup-plugin-commonjs" error in the runtime when I bundle and run my actual application. However, I can't understand what causes this error. 

I tried everything I could think of to reproduce the issue but I'm unable to do so. Here is [my best attempt](https://github.com/ceremcem/debug-ls/tree/fb57594b7ded076123610f1a36ccc73fc8838c01/example/dynamic-require):  

in my_node_modules/my-lib.ls:
```ls
some-state = Math.random() >= 0.5
if some-state
    require! './hey'
...
```

According to my knowledge (if I'm not wrong) this is absolutely a dynamic require which the requirement is decided in the runtime. However, rollup does not complain about it. 

`package.json` is [here](https://github.com/ceremcem/debug-ls/blob/fb57594b7ded076123610f1a36ccc73fc8838c01/package.json#L20-L27) and rollup version is 2.26.8.

Here is [my actual application](https://github.com/ceremcem/chibios-configurator/blob/c3792cc6b498f5010a9133f448f18371340cc0d4/servers/stm/template.ls) and here is [the bundled version](https://gist.github.com/f378161ac6a3c9a224567b6e06c7080c).

### Expected Behavior

An error to be thrown indicating the responsible file for "Dynamic requires are not currently supported by rollup-plugin-commonjs" error.

### Actual Behavior

Only the "Dynamic requires are not currently supported by rollup-plugin-commonjs" error is thrown, no clue for responsible file.

**Comment by shellscape** [comment]
Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates and the sections in them being _required_. Because portions of our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

Please also note that this isn't the right place to ask for support or help. Citing the issue templates:

> Hey there! If you need help or tech support then this is not the place to
ask. Please head to [the Rollup Gitter](https://gitter.im/rollup/rollup)
instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

>   👉🏽 Need help or tech support? Please don't open an issue!
  Head to https://gitter.im/rollup/rollup or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. Please try one of the avenues mentioned above (and in the issue templates).

**Comment by ceremcem** [comment]
Sorry for the inconvenience, I moved my question to StackOverflow.

**Comment by mjmnagy** [comment]
> 
> 
> Sorry for the inconvenience, I moved my question to StackOverflow.

Did you try updating `CommonJS` to the latest version? This seemed to fix the issue for me and present a whole wack of other ones
https://github.com/rollup/plugins/issues/563

**Comment by ceremcem** [comment]
> Did you try updating CommonJS to the latest version?

Yess! It worked in my case too. Thanks!

### Details

My bundle failed with the same "Dynamic requires are not supported" error but this time it pointed the problematic file: 

```
Error: Dynamic requires are not currently supported by @rollup/plugin-commonjs
    at commonjsRequire (/home/ceremcem/sync/curr-projects/aktos/chibi-configurator/servers/stm/__template.ls.js:40:8)
    at /home/ceremcem/sync/curr-projects/aktos/chibi-configurator/servers/stm/__template.ls.js:9832:21
        -> /home/ceremcem/sync/curr-projects/aktos/chibi-configurator/scada.js/lib/dcs/node_modules/jsondiffpatch/src/main.js:56:21
```

I examined the `src/main.js` and I verified the issue. Then I upgraded `jsondiffpatch`. Now it works very well.
