### ISSUE TITLE
Babel plugin returns namespace when imported from an ES module

### ISSUE THREAD

**Issue by vimtaai** [rollup/plugins#565]
- Rollup Plugin Name: `@rollup/plugin-babel`
- Rollup Plugin Version: 5.2.0
- Rollup Version: 2.26.10
- Operating System (or Browser): Win 10
- Node Version: 14.2.0
- Link to reproduction: https://repl.it/@vimtaai/rollup-plugin-repro

### Expected Behavior
Importing the `@rollup/plugin-babel` package in an ES Module returns the plugin funcition (like in other plugins).

### Actual Behavior
Importing the `@rollup/plugin-babel` package in an ES Module imports a namespaced version of the plugin.

### Additional Information
`@rollup/plugin-json`, `@rollup/plugin-commonjs`, `@rollup/plugin-node-resolve` all return the plugin function when imported from an ES Module. `@rollup/plugin-babel` behaves differently.

**Comment by Andarist** [comment]
This is a byproduct of how node's interop with CJS has been implemented. This is unfortunate, but it's correct according to its semantics. `module.exports` of a CJS file is being converted to a default export - other plugins work because they only export a single thing, the Babel plugin exports several though and thus this cannot be done.

We could fix this by providing conditional exports in package.json but that would, technically, be a breaking change for `@rollup/plugin-babel` and I think that this should be done collectively for all packages in this repo - if we think that it's time to do it. Each package needs to be evaluated to check if it would be a breaking change for it or not.

**Comment by vimtaai** [comment]
Well, ES Modules are note "experimental" anymore. Since Node 12 they are enabled by default, so it probably worth taking a look at ;)

**Comment by Andarist** [comment]
Actually - last i’ve checked they were still experimental, they have only been enables by default which is a very weird and confusing situation 🤷‍♂️

**Comment by shellscape** [comment]
Yeah ES Modules in Node < 14 is a mess.

**Comment by vimtaai** [comment]
Ok, I just checked, you are right. Experimental but enabled by default. Interesting choice.
Still, the conditional export solution would be nice. It would be a nice way to provide "forwards-compatibility".
@Andarist In the meantime what would you recommend for a temporary solution? I don't like the idea of having different kind of imports for different plugins. Maybe a helper file that works as an interface and reexports all plugins in a uniform format? 🤔
```js
import BabelPlugin from "@rollup/plugin-babel";

import jsonPlugin from "@rollup/plugin-json";
import commonjsPlugin from "@rollup/plugin-commonjs";
import nodeResolvePlugin from "@rollup/plugin-node-resolve";

import { terser as terserPlugin } from "rollup-plugin-terser";

export const json = jsonPlugin;
export const commonjs = commonjsPlugin;
export const babel = BabelPlugin.babel;
export const nodeResolve = nodeResolvePlugin;
export const terser = terserPlugin;
```

**Comment by shellscape** [comment]
@vimtaai given the age of the issue, we're going to close for housekeeping. If you'd like to submit a PR that would allow for the type of import you'd like to see, while keeping backcompat for non-ESM users, we'd be happy to take a look.
