### ISSUE TITLE
regeneratorRuntime is not defined with babelHelpers: 'bundled'

### ISSUE THREAD

**Issue by ricokahler** [rollup/plugins#570]
- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: v5.2.1
- Rollup Version: v2.26.11
- Operating System (or Browser): N/A
- Node Version: v12.13.1
- Link to reproduction _(⚠️ read below)_: https://repl.it/repls/CarefulNoxiousSysadmin#rollup.config.js

### Expected Behavior

I would think regenerator-runtime would be included in the bundle with the option `babelHelpers: bundled` but that doest not seem to be the case.

### Actual Behavior

`ReferenceError: regeneratorRuntime is not defined`

The regenerator runtime is not bundled.

### Additional Information

https://repl.it/repls/CarefulNoxiousSysadmin#rollup.config.js

Related: #356

**Comment by Andarist** [comment]
[This is how Babel works](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAKigUwM5QBQEoDeAUAJACeMaANgCaIAsATIQL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=) - `regeneratorRuntime` is not considered a helper, it doesn't come from Babel's core implementation but from the external module. You should either make it available globally or use `@babel/plugin-transform-runtime` appropriately: https://babeljs.io/docs/en/babel-plugin-transform-runtime#regenerator

**Comment by marcofugaro** [comment]
I am having this issue as well, how do I inject `regenerator-runtime` on top of my bundle without importing it directly from the library? (I have some builds with babel and some builds without)

**Comment by shellscape** [comment]
@marcofugaro please refrain from "me too" replies, and this is not the place for support.

**Comment by SoYoung210** [comment]
@marcofugaro how about use `babelHelpers: runtime` ?

**Comment by frozer** [comment]
@SoYoung210 It doesn't work too. I've provided a similar issue, because still haven't got an answer - https://github.com/rollup/plugins/issues/776#

**Comment by trev-dev** [comment]
> [This is how Babel works](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAKigUwM5QBQEoDeAUAJACeMaANgCaIAsATIQL5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=)

Having recently moved back to JS from TypeScript (where Async/Await is usually not an extra config step), I have come to realize the cost of using async/await after compile. Turns out that for just one keyword to save 2 lines of code, I am bloating every function definition by a factor of 5(ish) [Have a look at what I mean](https://babeljs.io/repl#?browsers=last%202%20versions%2C%20%3E%202%25&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsI2QUxMgCgEoYBvAKBhgCcdkFqsQ6AVVAWx3QUOIF4AfDCiYQ6ADY4AdOPQBzAgCIAEjnGzFRADQwATAAZDRANzkAvuXKIUGLLny7iZcgEha9RjAg4A7jAAK1OjsqMwEBLRi4gBuOCSCzlRULszIbJzcvPFCkRKxSqrq6ADMRESUSWYm5pbAPsCoyNh4hNUiEFHSsgoqarK6muRAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.8&externalPlugins=&assumptions=%7B%7D)

I think if Promises are written well enough, they are terse enough...at least, until async/await is more universally supported in browsers.
