### ISSUE TITLE
[commonjs]requireReturnsDefault for entry module

### ISSUE THREAD

**Issue by chengcyber** [rollup/plugins#580]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 15

### Expected Behavior / Situation

`requireReturnsDefault` also affects entry module

### Actual Behavior / Situation

`requireReturnsDefault` only affects static dependencies

### Modification Proposal

For now, commonjs plugin has a brand new option named `requireReturnsDefault`, it can be set to 'auto' to use `getDefaultExportFromNamespaceIfNotNamed` or set to `preferred` to use `getDefaultExportFromNamespaceIfPresent`, but it only works when resolving static dependencies. Could we bring this feature to even entry module?

See the code at https://github.com/rollup/plugins/blob/a6ff567c5ca3cdd21d92c1d0a5edb3fbf0506397/packages/commonjs/src/transform.js#L675

```
  const defaultExport =
    code.indexOf('__esModule') >= 0
      ? `export default /*@__PURE__*/${HELPERS_NAME}.getDefaultExportFromCjs(${moduleName});`
      : `export default ${moduleName};`
```

we can change a little bit to make it happen:

```
  let defaultExport = `export default ${moduleName};`
  if (code.indexOf('__esModule') >= 0) {
     if (requireReturnsDefault === 'auto') {
       defaultExport = `export default /*@__PURE__*/${HELPERS_NAME}.getDefaultExportFromNamespaceIfNotNamed(${moduleName});`
     } else if (requireReturnsDefault === 'preferred') {
       defaultExport = `export default /*@__PURE__*/${HELPERS_NAME}.getDefaultExportFromNamespaceIfPresent(${moduleName});`
     } else {
       defaultExport = `export default /*@__PURE__*/${HELPERS_NAME}.getDefaultExportFromCjs(${moduleName});`
     }
  }
```

**Comment by lukastaegert** [comment]
Two things:
- The option is called `requireReturnsDefault` and it is solely concerned what is `require` returns when importing an actual ES module from a CommonJS context. I do not understand why this option should also control what the inferred default export is when transforming a CommonJS module. I mean for starters, this is not an ES module that anyone would want to import. If you want changes here, it will likely need to be a different option.
- It would help instead of starting with solutions for an unknown problem if you rather described the issue you are facing. In what situations would it help if the default export were something different? I have a *guess* what this might be about, namely that there is no way to control default export auto-detection inside an ES module, but that is only a guess. Maybe this is what you want: https://github.com/rollup/rollup/pull/3787#issuecomment-694675174 ?

**Comment by chengcyber** [comment]
For the first thing, you are right. I just want the ability to do sth like `requireReturnsDefault` to the entry module when entry is cjs module and rollup output format is `esm`. I totally agree it could be better to name it as a different options.

For the second thing, I would like to use a demo project to describe more clear the problem I am facing. -> [rollup-interop-issues](https://github.com/chengcyber/rollup-interop-issues). Maybe the right solution is not my proposal.

The bundled `react-color` exports an unwanted default exports in my case. If I can control the entry module export with `getDefaultExportFromNamespaceIfNotNamed`. I can make the `import { ChromePicker } from 'react-color'` works.

I can really feel the frictions in the ecosystem, and realize the difficulty on solving them smoothly.  If this proposal is in a wrong direction in your mind, you can close the issue. and, I appreciate the works you are working.

P.S. After check the rollup#3787 issue, I am so looking forward to the world which is said as `we can implement sane defaults that make interop frictions a thing of the past and ideally get Webpack on board with that as well.`
