### ISSUE TITLE
[commonjs] commonjsHelpers.js generating circular dependencies

### ISSUE THREAD

**Issue by isidrok** [rollup/plugins#591]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 15.1.0
- Rollup Version: 2.28.2
- Operating System (or Browser): Windows
- Node Version: 14.12.0
- Link to reproduction _(⚠️ read below)_: https://github.com/isidrok/rollup-commonjs-circular-dependencies-bug

### Expected Behavior

Including '\0commonjsHelpers.js' doesn't cause circular dependencies when using manual chunks.

### Actual Behavior

Including '\0commonjsHelpers.js' can cause circular dependencies when using manual chunks.

### Additional Information

This is easily solvable by the user using manualChunks for that id. It may be enough documenting this and exporting the helper id by the plugin, so it doesn't need to be hard-coded.

```js
manualChunks(id){
  if(id === '\0commonjsHelpers.js'){return 'helpers';}
}
```

**Comment by lukastaegert** [comment]
Yes, the reason is that in your case, the helpers are used by files in two different manual chunks. When you use a function for manualChunks, the module will end up in the manual chunk that is resolved first. Thus, a circular dependency is created if there is also an import in the other directin.

I do not see how we could "fix" this on Rollup side. As it stands, the behaviour is deterministic albeit undesired. Your solution of placing the helpers in a separate chunk is probably the best here.

Another approach would be to use the object form of manualChunks instead, as that one allows to control the order in which manual chunks are created (the order is of course top to bottom). The goal is to place it in a chunk that does not have any other dependencies. This order does not create the circular dependency:

```js
export default {
    //...
    manualChunks: {
        b: ['src/b'],
        a: ['src/a'],
        c: ['src/c'],
    },
   //...
}
```

Still note that in any case, manualChunks will mess up your execution order, but that is inherent to the concept.

**Comment by isidrok** [comment]
I see, thanks for the insight. 

Just to be sure if I understand it correctly, if I have a configuration like this:

```js
manualChunks(id) {
    if (id.includes('node_modules')) {
        const dirs = id.split(path.sep);
        const name = dirs[dirs.lastIndexOf('node_modules') + 1];
        return name;
    }
}
```

There would be no problem as long as there are no relations of the form:

```
node_modules/a -> commonjsHelpers
node_modules/b -> commonjsHelpers
node_modules/a -> node_modules/b
```

In that case if 'node_modules/a' is generated first it will create a circular dependency. As this is _unpredictable_ then the safest approach is to emit a chunk for 'commonjsHelpers'.  Finally, in this particular case, execution order should not be altered since chunks will be executed as specified in the source code.

**Comment by MaxMotovilov** [comment]
Just hit a problem manifesting from the same root cause - had to spend a few hours with the debugger to identify it. In my case, the `\0commonHelpers.js` was being randomly assigned to the root bundle of the application making all other bundles directly dependent on it; thanks to import hoisting the root bundle also ended up dependent on itself!

I have [independently :stuck_out_tongue:] come up with the same workaround of manually assigning the offending chunk to a specific (library) bundle. It is acceptable in my use case, but I think another alternative would provide a safer default: replicating the chunk in each bundle that uses it. That way no spurious dependencies are introduced at a cost of a moderate increase in bundle size. Unfortunately, I don't have the first idea how to implement it in Rollup :disappointed:
