### ISSUE TITLE
inserting random `index.js#` into a require import containing a #. (breaking the import)

### ISSUE THREAD

**Issue by MarkLyck** [rollup/plugins#593]
Getting the following error trying to use memoizee with rollup:

```
Could not load /Users/mark/ypm/xxxx/cloud-one2/node_modules/es5-ext/array/index.js#/e-index-of (imported by node_modules/memoizee/normalizers/get-fixed.js): ENOENT: no such file or directory, open '/Users/mark/ypm/xxxx/cloud-one2/node_modules/es5-ext/array/index.js#/e-index-of'
```

I checked my node modules and `node_modules/es5-ext/array/#/e-index-of.js` exists.

I'm not sure why the import ends up being `es5-ext/array/index.js#/e-index-of` (there is no `index.js` in the require path)

Looking at the `get-fixed.js` inside memoizee in the node modules. The require is perfectly fine:

`var indexOf = require("es5-ext/array/#/e-index-of")`

My guess is that the `#` freaks out snowpack somehow? Honestly I've never seen a folder called `#` before, and have no clue why `es5-ext` decided that was a good idea. But other build systems have no problems handling this.

Sounds like the issue is that Rollup treats that as a URL, in which case "es5-ext/array/#/e-index-of" is really "es5-ext/array/" (anything after a hash in a URL isn't a part of the path itself).

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
