### ISSUE TITLE
Honor declaration config

### ISSUE THREAD

**Issue by amcdnl** [rollup/plugins#61]
It would be nice if the `declaration: true` flag would be honored in the output.

**Comment by shellscape** [comment]
Hey folks. We're in progress on migrating the plugin, and have transferred this issue. We're going to lock it for a short time until the migration is complete, and then we'll unlock and continue the discussion. 🍺

**Comment by timonson** [comment]
Is anybody working on this?

**Comment by NotWoods** [comment]
Yes, it's being worked on. Contributor support is also welcome!

**Comment by heynext** [comment]
any updates now?

**Comment by NotWoods** [comment]
Added in version 4.0.0 of the typescript plugin

**Comment by danimoh** [comment]
For others also potentially struggling with this: For types to be emitted, you currently have to declare a `rootDir` in `tsconfig.json`. This is related to https://github.com/rollup/plugins/issues/243. Even though the compilation does not fail when using `declarationDir` instead of `outDir` this does also apply when using `declarationDir`.

Also have a look at the PR that implemented this feature for instructions on how to generate declaration files: https://github.com/rollup/plugins/pull/217

**Comment by zeakd** [comment]
Thanks @danimoh very helpful.
Here's my rollup config to make [redux](https://github.com/reduxjs/redux/blob/master/rollup.config.js) style outputs.

- `output.dir` is required for `declaration: true` option.
- `declarationDir` folder should be inside `output.dir`.
- do not use `declaration` and `declarationDir` in **tsconfig.json**. `declarationDir` can't override using `@rollup/plugin-typescript`

``` js
import typescript from '@rollup/plugin-typescript'
import pkg from './package.json'

export default [
  // CommonJS
  {
    input: 'src/index.ts',
    output: {
      dir: './',
      entryFileNames: 'lib/my-pkg.js',
      format: 'cjs',
    },
    plugins: [
      typescript({
        declaration: true,
        declarationDir: 'types/',
        rootDir: 'src/'
      }),
    ]
  },

  // ES
  {
    input: 'src/index.ts',
    output: { file: 'es/my-pkg.js', format: 'es' },
    plugins: [
      typescript(),
    ]
  },
]
```

**Comment by imjeen** [comment]
Yes,  it's being worked. 

And get many `.d.ts` files if the source is not one file. 

There was any way to generate only one declaration file?

**Comment by DominicTobias** [comment]
Since I always get stuck on this when trying to use this package instead of `typescript2` (which works perfectly out the box) here's how to get declarations working with this one.

1. Even though it says you don't need to, you need to tell it the tsconfig path:

```ts
typescript({
  tsconfig: './tsconfig.json',
}),
babel({ babelHelpers: 'bundled', extensions }), // Note: DON'T need babel typescript preset (or this babel plugin unless you need to)
```

2. This will start to emit declarations but in the wrong directory, for example `dist/dist/<types here>` (it duplicates the folder). To fix this keep `"outDir": "./dist",` in `tsconfig.json` but remove it from the `output` of rollup, e.g.:

```
{
    file: './index.js', // don't do './dist/index.js' like you normal would
    format: 'esm',
    globals,
}
```

**Comment by shellscape** [comment]
> Since I always get stuck on this when trying to use this package instead of typescript2 (which works perfectly out the box) 

@DominicTobias I really wish you would leave the snark and slight out of replies. It doesn't serve any purpose, makes you look like a jerk, and is insulting to the folks who gave their free time to improve this plugin over time. Sure, it works different for people in different scenarios - as all things do - but that doesn't mean you need to disrespect who freely made something for you to use. Be a better person.

**Comment by betabandido** [comment]
@zeakd @danimoh Following your instructions I finally managed the plugin to output declarations 🎉 Thanks!!

I have a question, though. It seems `dir` and `file` cannot be both present at the same time in an output definition. Therefore, I don't seem to have any way to control the name of the file being generated (the name I add in the `main` field in package.json).

Is there any solution or workaround for this?
