### ISSUE TITLE
It should be clarified that plugin-commonjs should be placed before plugin-babel

### ISSUE THREAD

**Issue by shrinktofit** [rollup/plugins#620]
Since how `@rollup/plugin-commonjs` and `@rollup/plugin-babel` are implemented. It's better to hint user that when specify rollup plugins, they'd better place `@rollup/plugin-commonjs` before `@rollup/plugin-babel`.

## Reason

Given a module in CommonJS format and its code needs to be processed by babel. For example:
```js
module.exports = typeof window;
```

`@rollup/plugin-babel` will inject helper codes:
```js
import { typeof as _typeof } from "\0rollupPluginBabelHelpers.js";
module.exports = (typeof window === "undefined" ? "undefined" : _typeof(window));
```

then, the transformed source will be passed to `@rollup/plugin-commonjs`. The CommonJS plugin then treat the source as ES6 module(because of the `import` syntax `@rollup/plugin-babel` inserted) and does not process further and leads to `*** is not exported by ***`.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by shrinktofit** [comment]
@shellscape  I have now refiled the issue in https://github.com/rollup/plugins/issues/622
