### ISSUE TITLE
[!] TypeError: Cannot read property 'length' of undefined after @rollup/plugin-commonjs installed

### ISSUE THREAD

**Issue by Duzij** [rollup/plugins#638]
I want to use xml-js library with rollup bundler. After simple import I got an error, that 'json2xml' is not exported by node_modules\xml-js\lib\index.js
After installing @rollup/plugin-commonjs to fix this issue, I got this TypeError

`index.js → output...
[!] TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at new MagicString (C:\Users\x\AppData\Roaming\npm\node_modules\rollup\dist\shared\rollup.js:580:34)
    at Module.setSource (C:\Users\x\AppData\Roaming\npm\node_modules\rollup\dist\shared\rollup.js:10038:28)
    at ModuleLoader.addModuleSource (C:\Users\x\AppData\Roaming\npm\node_modules\rollup\dist\shared\rollup.js:18158:20)`

+-- @rollup/plugin-commonjs@16.0.0
+-- xml2js@0.4.23
+-- rollup@2.26.10

node -v v10.11.0

After intalling same packages to empty project, I got same error. Do you have any suggestions?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by mauriciovillam** [comment]
@Duzij I've got the same issue with node v10.19, can you share your package.json?
