### ISSUE TITLE
How to configure Dynamic -import-vars

### ISSUE THREAD

**Issue by ciycy** [rollup/plugins#664]
`import dynamicImportVars from '@rollup/plugin-dynamic-import-vars';

export default {
	plugins: [
		dynamicImportVars({
			// option
		})
	]`

How to configure option？？？？

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by softboy99** [comment]
Hi,
Not compatiable with vite 4.3.x, which has update rollup to 3.x. Currently, type error for Plugin and InputPluginOptions
