### ISSUE TITLE
Update plugins to be built with TypeScript 4

### ISSUE THREAD

**Issue by benmccann** [rollup/plugins#679]
- Rollup Plugin Name: various
- Rollup Plugin Version: `master`

### Expected Behavior / Situation

I would like the plugins to be built with TypeScript 4 so that we are using the latest version

### Actual Behavior / Situation

`package.json` contains `"typescript": "^3.9.7",`

### Modification Proposal

Update `package.json` to `"typescript": "^4.0.0",`. Here's a commit showing the other required changes: https://github.com/rollup/plugins/pull/674/commits/8d07a42cdc03188ae14107c439f70a976af8d33c

What is the process for this? Do we need to update one plugin at a time?

**Comment by shellscape** [comment]
I'm going to update the `CONTRIBUTING` doc to cover this question. Updating multiple plugins at once isn't something we'd like to encourage;  mostly because it requires a super clean commit history in the feature branch, but also because multiple plugin updates are harder for contributors to review, and we've got a lot of folks that only tend to one or two plugins here. To make matters more murky, it looks like the typescript dependency is at the root, so that makes things nice and uniform but also tricky.

For the sake of expediency for this effort, I'd say tackle one at a time, and add the updated typescript dependency to each plugin being worked on. (We can do a follow up commit later to remove this deps if needs be). I do also want to raise awareness in this issue that we have a lot of plugins that we haven't been able to get around to converting to TS, and that's likely more important than updating the TS version, but it's hard to say for certain because one could argue that it'd be easier to do on an updated version of TS.

**Comment by benmccann** [comment]
There's about 20 different packages that currently use TypeScript. Once https://github.com/rollup/plugins/pull/674 is merged the only change necessary to the others is bumping the TypeScript version. None of the others require code changes and it will not create any backwards incompatibilities. I'm not sure if it's an effective use of time to create 20 different PRs all bumping the version for the same package.

Is this something that would be possible for a maintainer to bump them all in one go? This really seems like something that could be a 1-line change. I would understand if there were code changes to the individual packages, but it doesn't seem like a dependency bump with no code change should need individual reviews from 20 different package maintainers. I don't really see what the risk is.

**Comment by benmccann** [comment]
The individual plugins are using TypeScript 4 now. Should we remove the TypeScript version from the base `package.json` or should we set the base version to version 4 and remove the version from the sub-packages?

**Comment by shellscape** [comment]
I'd update the base. It'll be a while before we have to do another major version bump of that.

**Comment by shellscape** [comment]
With all of the PRs for this update merged, we should be good to close this.
