### ISSUE TITLE
seems like ponyfill.js is one of the common elements in a few of the issues reported/linked here:

### ISSUE THREAD

**Issue by dominicg666** [rollup/plugins#697]
seems like ponyfill.js is one of the common elements in a few of the issues reported/linked here:

node_modules/symbol-observable/es/index.js
```
import ponyfill from './ponyfill.js';
```

Looking at the code behind that you find this:
```
export default function symbolObservablePonyfill(root) {
	var result;
	var Symbol = root.Symbol;

	if (typeof Symbol === 'function') {
		if (Symbol.observable) {
			result = Symbol.observable;
		} else {
			result = Symbol('observable');
			Symbol.observable = result;
		}
	} else {
		result = '@@observable';
	}

	return result;
};
```
and that was last updated 4 years ago specifically to support rollup:

https://github.com/benlesh/symbol-observable/commit/7a41de9d83d2e8ecddc4fdda6f1d3b2182f61053

https://github.com/benlesh/symbol-observable/blob/master/es/ponyfill.js

Maybe it's time for a rewrite?...

_Originally posted by @eswat2 in https://github.com/rollup/plugins/issues/304#issuecomment-615009410_

**Comment by dominicg666** [comment]
How to solve this issue?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by dominicg666** [comment]
I sharing below when I'm faceing issue

 microbundle-crl watch --no-compress --format modern,cjs
Watching source, compiling to dist:
Error: 'import' and 'export' may only appear at the top level

at /home/dominic/Neoito/real-time-module/Frontend/node_modules/symbol-observable/es/index.js:2:0

1: /* global window */
2: import ponyfill from './ponyfill.js';
   ^
3: 
4: var root;
