### ISSUE TITLE
[@rollup/plugin-typescript] Cannot make repl.it reproductible test case

### ISSUE THREAD

**Issue by cdalexndr** [rollup/plugins#699]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.0.0
- Rollup Version: 1.27.14
- Operating System (or Browser): repl.it
- Node Version: 1.27.14
- Link to reproduction _(⚠️ read below)_: https://repl.it/@cdalexndr/rollup-plugin-repro-1

### Expected Behavior
Compilation successful.

### Actual Behavior
```
>npx rollup -c

input.ts → output.bundle.js...
[!] (plugin typescript) TypeError: program.close is not a function
TypeError: program.close is not a function
    at Object.buildEnd (/home/runner/rollup-plugin-repro-1/node_modules/@rollup/plugin-typescript/dist/index.js:712:75)
    at /home/runner/rollup-plugin-repro-1/node_modules/rollup/dist/rollup.js:12899:25
    at async Promise.all (index 0)
```

### Additional Information
I'm trying to make a reproductible test case for an issue that got closed.
I'm using rollup with typescript, so I only have `.ts` files that get compiled into bundles.

**Comment by shellscape** [comment]
OK I'd really like to give you the benefit of the doubt here, but I'm struggling. The second option is to put together a minimal repo which demonstrates the problem. If you're struggling to setup a REPL using that template, then the reproduction probably requires local execution, and that's why we have the repo as an option.

Our issues here aren't for triaging REPL.it so any issues with that should be taken up with them.

I'm closing this issue, and would ask you not to open further issues like it. If you'd like to us to triage your other issue, which was closed for lack of a reproduction, please create one and reply to your closed issue (#698) with the link to the reproduction. (Be sure to _read the instructions_ on what makes a reproduction minimal. If we get dropped a 1000 line app, we're not going to triage it.) Once a reproduction is added, we'll reopen. Participating here really isn't this complicated - dozens of folks follow the instructions every day and we're able to help a lot of the folks. Take the time to read what's in the issue templates you're filling out.

**Comment by cdalexndr** [comment]
Ok, I was hoping you have some repl.it template for typescript.
Seems that only solution is to make a repository, as neither `repl.it` nor `rollupjs.org/repl/` seem to be suited for typescript test cases.

**Comment by shellscape** [comment]
We actually get a lot of typescript reproductions via REPL.it.  https://github.com/rollup/plugins/labels/%F0%9F%94%8C%20plugin-typescript there are several bug issues there with TS reproductions in REPL.it
