### ISSUE TITLE
Does rollup allow us dynamic change input entries?

### ISSUE THREAD

**Issue by tianyingchun** [rollup/plugins#730]
HI, rollup team, i have an quest, while we use rollup. `watch` to start watch some entries with `input` configuration.

if watched entry files has any change, it will trigger rebuild automatically, but i have question, can we allow to dynamic modify entry `input` e.g. before i passed input: ['src/index.ts'] maybe in some conditions, i need to add another entry point into it `['src/index.ts', 'src/another/ts']. if we don't want to restart the watch process. how to do it?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
