### ISSUE TITLE
strip plugin doesn't work

### ISSUE THREAD

**Issue by Marckon** [rollup/plugins#739]
I use `gulp` to output some assets, and the project is `typescript` , my gulpfile is like below. When I simply add a strip plugin, the output file still has `console.*` function. Specifyng optionals for strip also doesn't help.

```javascript
gulp.task('build', () => {
  return del('./lib').then(() => {
    return rollup
      .rollup({
        input: 'src/index.ts',
        plugins: [
          strip(),
          typescript({
            typescript: ttypescript,
            useTsconfigDeclarationDir: true,
            tsconfigDefaults: {
              compilerOptions: {
                plugins: [
                  { transform: 'typescript-transform-paths' },
                  {
                    transform: 'typescript-transform-paths',
                    afterDeclarations: true,
                  },
                ],
              },
            },
          }),
        ],
      })
```

**Comment by Marckon** [comment]
I eventually use a gulp plugin `gulp-strip-debug`, and it works.😷

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by mmiszy** [comment]
I have the same problem, the plugin just doesn't do _anything_ for me.

**Comment by shellscape** [comment]
Please remember that we don't allow "me too" replies in this depo unless it's accompanied by additional diagnostics info that aids in triage.
