### ISSUE TITLE
[replace] API: move options to separate object

### ISSUE THREAD

**Issue by milahu** [rollup/plugins#748]
in `@rollup/plugin-replace@2.3.4`, options are mixed with search-replace pairs, which is ugly
and we cannot replace the words `delimiters`, `exclude`, `include`

```js
export default {
  plugins: [
    replace({
      changed: 'replaced', // search-replace pair
      delimiters: ['', ''], // option
    })
  ]
};
```

expected API:

```js
export default {
  plugins: [
    replace({
      // search-replace pairs
      changed: 'replaced',
      changed2: [ 'replaced2', { delimiters: ['', ''] } ], // local options for one replacement
      }, {
      // global options for all replacements
      delimiters: ['', ''],
    })
  ]
};
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
