### ISSUE TITLE
Updating to @rollup/plugin-commonjs@17.0.0 breaks svelte application

### ISSUE THREAD

**Issue by rsheasby** [rollup/plugins#757]
There seems to be an issue with the new es module reconstruction feature in 17.0.0 https://github.com/rollup/plugins/pull/537.

Everything was working without issue initially, but when I tried to upgrade my npm dependencies including this plugin to 17.0.0, I started getting the following error in my browser:

```
Uncaught ReferenceError: exports is not defined
```

When looking at my bundle, the `Object.defineProperty(exports, "__esModule",` statements are no longer being compiled away for some reason.

I'm unsure if this is a bug, or just a configuration problem relating to the new feature being enabled by default? If it is just a configuration change that needs to be made with the update, it's probably worth documenting this somewhere.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
