### ISSUE TITLE
Updating to @rollup/plugin-commonjs@17.0.0 breaks svelte application using Amplify libs

### ISSUE THREAD

**Issue by rhard** [rollup/plugins#762]
- Rollup Plugin Name: plugin-commonjs
- Rollup Plugin Version: 17.0.0
- Rollup Version: 2.3.4
- Operating System (or Browser): Windows/Chrome
- Node Version: 15.5.1
- Link to reproduction _(⚠️ read below)_: https://repl.it/@RhardRoman/rollup-plugin-repro

### Expected Behavior

The project can be build and viewed in Chrome

### Actual Behavior

After updating plugin-commonjs to 17.0.0 and using @aws-amplify/core the Chrome throws an error:

```js
Uncaught ReferenceError: exports is not defined
    at CryptoOperation.js:2
    at main.js:31
```

Error source:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=CryptoOperation.js.map
```
### Additional Information

Just adding the Amplify core lib stops the project from working. With 16.0.0 everything is OK.

```js
import Amplify from '@aws-amplify/core';

Amplify.configure();
```

**Comment by shellscape** [comment]
Thanks for opening an issue. I'd recommend that you drill down into your reproduction, removing component parts until the issue resolves. Your reproduction is using several third party plugins which may be affecting how things are supposed to work. If you feel that `@aws-amplify/core` is the cause, I'd start with an empty project using commonjs and node-resolve to see if that's actually the issue (I'd be relatively surprised if it was). I'd bet it's a combination of things not necessarily related to commonjs that is causing your issue. Otherwise we'd probably be getting a flood of issues with Svelte so reliant on Rollup.

**Comment by rhard** [comment]
Hi @shellscape 
I'm quite new to JavaScript (be C++ programmer). Could you point me to what I need to remove from the project? I thought the project is almost empty and I provided smallest (basically Hello World from Svelte plus Amplify initialization). I think if I remove something the Svelte stops from working.

After I did a yarn upgrade yesterday the project breaks. I spend whole day finding the issue. Today I compared old running backup and found only difference is plugin-commonjs version. After rolling back everything is fine.

BTW: there is another issue here closed by the bot https://github.com/rollup/plugins/issues/757

**Comment by geigerzaehler** [comment]
I’ve created a minimal example that produces invalid output (https://gist.github.com/geigerzaehler/4dfb412e62ae9676b09e47a6b6ee97f0). The bundle does not correctly wrap the “empty” module and references `exports` which would crash the browser. The culprit “empty.js” is a file that is commonly generated by typescript for empty modules and included in a number of packages.

**Comment by shellscape** [comment]
cc: @LarsDenBakker @danielgindi @lukastaegert
