### ISSUE TITLE
[rollup-replace] How to deal with the problem of TS error after the replacement code?

### ISSUE THREAD

**Issue by asins** [rollup/plugins#841]
I use rollup-replace as the variable switch of the builder in the project, but I have encountered a problem when using it with TypeScript, and I always give me errors like this:

> semantic error TS2367: This condition will always return'true' since the types'boolean' and'string' have no overlap.

I will write code like this in my code

```ts
// a.ts
import Prod from './prod';
import Pre from './pre';
If(process.env.PROD === ’true’){
  console.log(‘is prod’);
  Prod.init();
} else {
  console.log(‘is pre’);
  Pre.init();
}
```

```js
// rollup.config.js
export default [
{
  input: 'src/index.ts',
  output: { file: 'dist/index.js', format: 'iife' },
  plugins: [
      replace({ values: { 'process.env.PROD': JSON.stringify('true') }, preventAssignment: true }),
      resolve({ browser: true }),
      commonjs(),
      typescript(),
  ]
}
]
```

In the above build code, `replace` needs to precede `resolve`, because it is necessary to use `replace` to avoid useless JS from being `imported` into the bundle file.

Who can help me solve this meaningless error message?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by alphawq** [comment]
@asins use typescript plugin before replace plugin
```ts
// rollup.config.js
export default [
  {
    input: 'src/index.ts',
    output: { file: 'dist/index.js', format: 'iife' },
    plugins: [
        typescript(),
        replace({ values: { 'process.env.PROD': JSON.stringify('true') }, preventAssignment: true }),
        resolve({ browser: true }),
        commonjs(),
    ]
  }
]
```
