### ISSUE TITLE
Problems caused by code's order

### ISSUE THREAD

**Issue by Veiintc** [rollup/plugins#846]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version:17.1.0
- Rollup Version:2.42.3
- Operating System (or Browser):
- Node Version:14.6.8
- Link to reproduction _(⚠️ read below)_:
https://github.com/electron-userland/electron-builder/issues/4530
https://github.com/vitejs/vite/issues/1421
I have the same error like this

### Actual Behavior
![image](https://user-images.githubusercontent.com/32948063/112664906-58c6a880-8e0f-11eb-821d-357a0b11657e.png)
![image](https://user-images.githubusercontent.com/32948063/112664948-611ee380-8e0f-11eb-9eb0-5a47565174c0.png)

It look like Problems caused by code's order

**Comment by Veiintc** [comment]
When I move 19822 before 15990,it work

**Comment by shellscape** [comment]
thanks for opening an issue. in this repository we require a minimal reproduction. That's why we offer the different options for providing one in the issue template. if you are choosing a repository for a reproduction, please see the provided link about what a minimal reproduction is. we don't have the resources to debug a large project for you unfortunately. this is why we ask that everybody provide a proper reproduction

**Comment by Veiintc** [comment]
this is the Link to  reproduction：
https://github.com/Veiintc/code_order
npm i
npm run build
npm start

**Comment by Veiintc** [comment]
the @rollup/plugin-commonjs's options

      dynamicRequireTargets:[

            'node_modules/electron-updater/out/*.js',

            'node_modules/electron-updater/out/differentialDownloader/*.js',

            'node_modules/electron-updater/out/providers/*.js'

      ],
It's work to me
