### ISSUE TITLE
[rollup-plugin-typescript] Unresolved dependency in Lerna monorepo

### ISSUE THREAD

**Issue by mgrisole** [rollup/plugins#870]
Hi guys, first of all thanks for all the good work on this plugin !

I am trying to configure a monorepo using Lerna and for an obscure reason rollup is yelling the following error on build time:

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@dktunited/oneshop-widgets-shared-utils (imported by src/main.ts)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
@dktunited/oneshop-widgets-shared-utils (guessing 'oneshopWidgetsSharedUtils')
```

Weirdly enough I am not getting any issue of this kind from a [Rush](https://rushjs.io/) monorepo while having exactly the same code for both the Svelte package and the shared typescript one.

I made a really simple reproduction repo here: https://github.com/mgrisole/svelte-typescript-monorepo-sample

If anyone has any clue on where the problem could come from I would really be grateful.

**Comment by shellscape** [comment]
Hey thanks for opening an issue. Unfortunately this isn't the right place to ask for support. Citing the issue templates:

>  👉🏽 Need help or tech support? Please don't open an issue!
>  Head to https://is.gd/rollup_chat or https://stackoverflow.com/questions/tagged/rollupjs

Apologies, but we don't have the bandwidth to service both support requests and technical issues for Rollup. Please try one of the avenues mentioned above (and in the issue templates).

**Comment by Mister-Hope** [comment]
Emmm, I am facing this issue too. I am using monorepo to provide different packages with different contents. 

Basiclly I wanna **import and bundle ts files in other packages in monorepo**. Because these packages are already outputing bundled code, so using that code could leed to duplicate util functions. That's why I want to import source code written by ts in other packages.

I am struggling with rollup on this, and **I DO think that currently rollup is not supporting it**. I cannot make `typescript` `nodeResolve` and `commonjs` work together when importing a ts code from another packages.

But I can easily make this on webpack.

@shellscape So can a feature request like this be supported?
