### ISSUE TITLE
vite use web3.js throw Uncaught ReferenceError: process is not defined 

### ISSUE THREAD

**Issue by 1329778364** [rollup/plugins#902]
To solve the problem "global is not defined "  
`import { defineConfig, UserConfigExport, ConfigEnv } from 'vite'
import vue from '@vitejs/plugin-vue'
import path from 'path';
import polyfillNode from 'rollup-plugin-polyfill-node'

export default defineConfig({
  plugins: [
    vue(),
    polyfillNode()
  ],
  optimizeDeps: {
    exclude: ['dragula'] // <- modules that needs shimming have to be excluded from dep optimization
  }
})` 
and  then throw  Uncaught ReferenceError: process is not defined, problem .
so How can I fix it?  thanks!
![image](https://user-images.githubusercontent.com/19623957/122024848-63378380-cdfb-11eb-89d6-9a97184fa324.png)

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by edeuxk** [comment]
To solve process issue:
On vite.config.{js}{ts}
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  define: {
    'process.env': {}
  }
})
```
