### ISSUE TITLE
Is there any option same as "cacheDirectory" option of babel-loader?

### ISSUE THREAD

**Issue by iceleo-com** [rollup/plugins#906]
I wonder if you provide an option the same as "cacheDirectory" option of babel-loader in your babel plugin?

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
