### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by CWSites** [rollup/plugins#912]
This was happening on version `5.0.1` as well.

`@rollup/plugin-url@6.0.0" has unmet peer dependency "rollup@^1.20.0||^2.0.0`

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by CWSites** [comment]
https://github.com/rollup/plugins/issues/917
