### ISSUE TITLE
New defaultIsModuleExports option

### ISSUE THREAD

**Issue by guybedford** [rollup/plugins#948]
### Feature Use Case

Currently with the CommonJS plugin you have to choose between Node.js style interop with CommonJS or browser style interop. There is no option that can work for both making compat mutually exclusive.

### Feature Proposal

The idea would be for a `defaultIsModuleExports: 'compat'` option which uses the pattern:

```js
import * as m from 'cjs';
const moduleExports = m.default || m;
```

Where the `default` is used if it exists, otherwise falling back to the namespace.

This might allow for compatibility with Node.js interop as well as Babel interop cases in more scenarios.

**Comment by lukastaegert** [comment]
Sounds good and aligns what Rollup core currently uses for external default imports with `output.interop: true`, though that is a slightly extended version, and it is not used for namespace imports:

```js
function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }
```

However for internal imports, you do not need the extra checks when doing a namespace import, so your approach looks good to me.

On a side not, I originally wanted to deprecate `output.interop: true`, but if you think it makes sense to be kept around, maybe we can rename the value to `"compat"` and extend it so that it also changes how namespace imports are resolved.

**Comment by guybedford** [comment]
Glad to hear you think it is a good option. One thing that is worth noting is that `output.interop` could be handled differently between CJS imports and ESM imports.

Ideally we would only include the interop in the CJS importing case, so that perhaps we can entirely deprecate `output.interop` and fully handle the "messy interop" patterns in the CommonJS plugin? Let me know if that fits your ideas here.

What I like about this is that it ensures that ES module semantics remain the straightforward specified ones as much as possible.

In terms of better supporting namespaces etc, I'm a little weary of an overly complex interop pattern, but it definitely could be an option.

**Comment by lukastaegert** [comment]
I do not think we can deprecated it in core as we still need it for other formats like AMD and for pure ESM code-bases that do not use the CommonJS plugin.

**Comment by guybedford** [comment]
Perhaps we could at least deprecate it only for ESM output though. Even for pure ESM code bases, they shouldn't need fancy interop patterns but could just use the expected native interop patterns with CJS at this point. Webpack has done a lot of work to align with this so it is possible now.
