### ISSUE TITLE
[commonjs] `transformMixedEsModules` incorrectly removes the `typeof module !== 'undefined'` guard, resulting in runtime error

### ISSUE THREAD

**Issue by sodatea** [rollup/plugins#970]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 20.0.0
- Rollup Version: 2.56.0
- Operating System (or Browser): Ubuntu 20.04
- Node Version: v12.16.1
- Link to reproduction _(⚠️ read below)_: https://replit.com/@sodatea/rollup-moment-commonjs-compat#dep.js

### Expected Behavior

The following condition:
```js
if (
  typeof module !== 'undefined' &&
  module &&
  module.exports
)
```

Should either be replaced as a whole by `true`, or left as-is.

### Actual Behavior

The code is transformed into:

```js
if (
  module &&
  module.exports
)
```

Without the `typeof module !== 'undefined'` guard, the code throws an `RefenceError` in a runtime without a global `module` variable.

### Additional Information

It only happens when `transformMixedEsModules` is enabled.

I found this bug when looking into https://github.com/vitejs/vite/issues/4113

`transformMixedEsModules` is required because the upstream `antd-mobile` library distributes mixed es modules.

The `if` expression is found in its dependency `moment`: https://github.com/moment/moment/blob/e96809208c9d1b1bbe22d605e76985770024de42/src/lib/locale/locales.js#L69-L74

So, I guess it may be a common problem.
After all, it makes sense that a library depending on `moment` would have more technical debts, such as mixed ES modules.

**Comment by shellscape** [comment]
Please search all the issues for "transformMixedEsModules" I believe there are a few that address the same concern

**Comment by sodatea** [comment]
I didn't find any issue that addresses the same bug.

**Comment by sodatea** [comment]
I have a rough idea of where this bug is from:

1. The `typeof` expression is replaced at https://github.com/rollup/plugins/blob/6463b9635e20b8425599f14005b9efdd8f94ecd6/packages/commonjs/src/transform-commonjs.js#L404-L422. This won't be executed for ES modules unless `transformMixedEsModules: true` is set;
2. A normal CommonJS module would be wrapped, so `module` would be accessible in its scope, thus no error. But a mixed module won't: https://github.com/rollup/plugins/blob/6463b9635e20b8425599f14005b9efdd8f94ecd6/packages/commonjs/src/transform-commonjs.js#L445-L449 Thus the issue.

**Comment by shellscape** [comment]
Thanks for taking the time to triage (really, we don't get a lot of help with that). @guybedford any thoughts on these findings?

**Comment by guybedford** [comment]
Definitely agreed it would be nice to fix this. There are two main approaches I'd suggest:

1. Don't do the replacement at all (easy fix, but may be a technical debt in future):
* When replacing a `typeof module !== 'undefined'`, run a `isModuleMemberExpression(parent)` check.
* If `isModuleMemberExpression` returns true, don't do the replacement.
* In `isModuleModuleExpression`, a logical expression would get the `left` and `right` slots checked in turn.
* When `isModuleMemberExpression` sees a member expression of object with identifier `module` it then returns true, and false otherwise.

2. Implement a better static analysis to replace the whole expression (better approach, but may be a little more work):
* When replacing a `typeof module !== 'undefined'`, run a `isModuleExpression(parent)` check, and loop this check through up the parent hierarchy until this returns false.
* As soon as it returns false, run `staticEval` on the last parent that returned true.
* For the implementation of `staticEval` as a sort of mini interpreter on a subset of JS (for now just logical expressions and member expressions is fine), see eg https://github.com/vercel/nft/blob/main/src/utils/static-eval.ts for how this sort of analysis can work.
* `staticEval` would then be primed with a `module` value that knows eg `exports` is a property and its type, so that the static eval can use that.
* If implemented properly that `staticEval` should then return the `true`, and that can be used to do the inlining.
