### ISSUE TITLE
How to make the output of TS definition files in the lib folder instead of lib/lib

### ISSUE THREAD

**Issue by Feafortecsy** [rollup/plugins#978]
## The directory structure
![image](https://user-images.githubusercontent.com/31724313/130176756-c6fdf40b-e8c3-41a8-88ca-97e10b0d5532.png)
## My config

```json
// tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "./lib",
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "allowJs": false,
    "strict": true,
    "noUnusedLocals": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "declaration": true,
    "declarationDir": "./lib",
    "declarationMap": false,
    "lib": [
      "esnext",
      "dom"
    ],
    "types": [
      "node",
    ]
  },
  "include": [
    "src/*"
  ]
}
```

```json
// rollup.config.ts
export default {
  input: 'src/index.ts',
  output: [
    {
      file: 'lib/index.js',
      format: 'cjs',
    },
    {
      file: 'lib/index.esm.js',
      format: 'esm',
    },
    {
      file: 'lib/index.umd.js',
      format: 'umd',
      name: 'ShawUtil',
    },
  ],
  plugins: [
    nodeResolve(),
    commonjs(),
    babel({
      babelHelpers: 'bundled',
      exclude: 'node_modules/**',
    }),
    typescript({
      tsconfig: './tsconfig.json'
    }),
    eslint({
      include: ['src/**'],
      exclude: 'node_modules/**',
    })
  ]
};
```

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by Axxxx0n** [comment]
Just change declarationDir

```javascript 
{"declarationDir": "."}
```

**Comment by vighnesh153** [comment]
@Axxxx0n but why does setting `declarationDir` to `.` creates the declaration files under `lib` or `dist` and setting it to `dist` or `lib`, creates the files under `dist/dist` or `lib/lib`? Doesn't make sense.
