### ISSUE TITLE
"__api is not a function" error ( v 3.0.0 ), not getting error in other project (v2.4.x) ?

### ISSUE THREAD

**Issue by ethanchiasson** [rollup/plugins#980]
I am following a supabase guide that I followed a few months back and the other project seems to work fine, however, now I get an error on `__api` saying it is undefined. Does anyone know why __api is not defined. when using @rollup/plugin-replace ?

replace({
            __api: JSON.stringify({
                env: {
                    isProd: production,
                    ...config().parsed // attached the .env config
                }
            }),
        }),
        json(),
        

        
        
--------------------------------------------------------------
 
 
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = __api.env.SVELTE_APP_SUPABASE_URL
const supabaseAnonKey = __api.env.SVELTE_APP_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
